package fwj.aniss.api.content.service;

import static fwj.aniss.api.content.model.ContentWorkflowConstants.STATUS_GENERATED;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.LinkedHashSet;
import java.util.Set;

import org.springframework.stereotype.Component;

import fwj.aniss.api.content.dto.ContentWorkflowDto.GenerateContentRequest;
import fwj.aniss.api.content.entity.GeneratedContent;
import fwj.aniss.api.content.entity.SourceItem;

@Component
public class DeterministicContentGenerator {
    public GeneratedContent generate(SourceItem sourceItem, GenerateContentRequest request) {
        String category = firstNonBlank(sourceItem.getCategory(), request == null ? null : request.contentType(), "general");
        String language = firstNonBlank(request == null ? null : request.language(), "en");
        String contentType = firstNonBlank(request == null ? null : request.contentType(), contentTypeForSource(sourceItem));
        String persona = firstNonBlank(request == null ? null : request.targetPersona(), "foreign workers and residents in Korea");
        String originalLink = firstNonBlank(sourceItem.getPublishableLinkUrl(), sourceItem.getCanonicalUrl(), sourceItem.getSourceUrl(), "");
        String title = generateTitle(sourceItem, contentType);
        String summary = generateSummary(sourceItem);
        String whyItMatters = whyItMatters(contentType, category, persona);
        String checkNext = checkNext(contentType, sourceItem);
        String disclaimer = disclaimer(contentType, sourceItem);
        String hashtags = hashtags(sourceItem, contentType);
        String imagePrompt = imagePrompt(contentType, category, title);
        String writtenContent = writtenContent(title, summary, whyItMatters, checkNext, disclaimer, originalLink);

        return GeneratedContent.builder()
                .sourceItemId(sourceItem.getId())
                .contentType(contentType)
                .category(category)
                .subcategory(firstNonBlank(sourceItem.getSubcategory(), ""))
                .targetPersona(persona)
                .language(language)
                .title(title)
                .writtenContent(writtenContent)
                .shortSummary(summary)
                .whyItMatters(whyItMatters)
                .checkNext(checkNext)
                .hashtags(hashtags)
                .imageUrl("")
                .imagePrompt(imagePrompt)
                .sourceDisclaimer(disclaimer)
                .translationYn(!language.equalsIgnoreCase(firstNonBlank(sourceItem.getLanguage(), language)))
                .translatedFrom(firstNonBlank(sourceItem.getLanguage(), ""))
                .originalLink(originalLink)
                .generatedAt(OffsetDateTime.now())
                .generationModel("rule-based-mvp")
                .qualityScore(qualityScore(sourceItem))
                .riskScore(riskScore(sourceItem.getSourceRiskLevel()))
                .status(STATUS_GENERATED)
                .statusReason("Generated by deterministic MVP template.")
                .build();
    }

    private String generateTitle(SourceItem sourceItem, String contentType) {
        String baseTitle = firstNonBlank(sourceItem.getTitle(), sourceItem.getSummaryText(), "Korea information update");
        if (baseTitle.length() > 120) {
            baseTitle = baseTitle.substring(0, 120).trim() + "...";
        }
        return switch (contentType) {
            case "JOB_GUIDE" -> prefixIfMissing(baseTitle, "Job update");
            case "VISA_GUIDE" -> prefixIfMissing(baseTitle, "Visa check");
            case "LIVING_TIP" -> prefixIfMissing(baseTitle, "Living in Korea");
            case "COMMUNITY_FAQ" -> prefixIfMissing(baseTitle, "Community question");
            default -> baseTitle;
        };
    }

    private String generateSummary(SourceItem sourceItem) {
        String raw = firstNonBlank(sourceItem.getSummaryText(), sourceItem.getBodyText(), sourceItem.getTitle(), "");
        return truncate(raw, 520);
    }

    private String whyItMatters(String contentType, String category, String persona) {
        return switch (contentType) {
            case "JOB_GUIDE" -> "This helps " + persona
                    + " screen employment information before spending time on applications or calls.";
            case "VISA_GUIDE" -> "Visa and stay rules can affect work eligibility, deadlines and required documents.";
            case "LIVING_TIP" -> "This turns practical " + category
                    + " information into a checklist that can be verified from the source.";
            case "COMMUNITY_FAQ" -> "Repeated community questions show where plain-language official guidance is needed.";
            default -> "This highlights source-backed information that may affect daily decisions in Korea.";
        };
    }

    private String checkNext(String contentType, SourceItem sourceItem) {
        String sourceName = firstNonBlank(sourceItem.getSourceName(), sourceItem.getSourcePlatform(), "the source");
        return switch (contentType) {
            case "JOB_GUIDE" -> """
                    1. Open the original job posting and confirm the deadline.
                    2. Check work location, contract type, salary basis and visa compatibility.
                    3. Contact the employer or Work24/WorkNet before sharing personal documents.""";
            case "VISA_GUIDE" -> """
                    1. Confirm the latest date on the official page.
                    2. Match the guidance to your visa type, stay period and employment status.
                    3. Call 1345 or visit immigration before making legal or visa decisions.""";
            case "LIVING_TIP" -> """
                    1. Check whether the information applies to your region and status.
                    2. Save the source link before visiting an office, bank, hospital or service provider.
                    3. Ask """ + sourceName + " or a qualified professional before signing or paying.";
            default -> """
                    1. Review the original source link.
                    2. Confirm the latest date and eligibility.
                    3. Treat this as a guide, not as final legal, financial or medical advice.""";
        };
    }

    private String disclaimer(String contentType, SourceItem sourceItem) {
        String sourceName = firstNonBlank(sourceItem.getSourceName(), "original source");
        String base = "Source-backed draft from " + sourceName + ". Verify the original source before taking action.";
        return switch (contentType) {
            case "VISA_GUIDE" -> base + " This is not legal advice.";
            case "LIVING_TIP" -> base + " For finance or healthcare topics, ask a qualified professional.";
            case "JOB_GUIDE" -> base + " Job conditions may change or close without notice.";
            default -> base;
        };
    }

    private String hashtags(SourceItem sourceItem, String contentType) {
        Set<String> values = new LinkedHashSet<>();
        values.add("WorkConnectKorea");
        values.add("WorkInKorea");
        values.add(contentType.replace("_", ""));
        values.add(firstNonBlank(sourceItem.getCategory(), "KoreaInfo").replaceAll("[^A-Za-z0-9]", ""));
        values.remove("");
        return values.stream().map(value -> "#" + value).reduce((left, right) -> left + " " + right).orElse("#WorkConnectKorea");
    }

    private String imagePrompt(String contentType, String category, String title) {
        return "Clean editorial image for foreign residents in Korea, topic: "
                + category + ", content type: " + contentType + ", title: " + title;
    }

    private String writtenContent(
            String title,
            String summary,
            String whyItMatters,
            String checkNext,
            String disclaimer,
            String originalLink) {
        return """
                %s

                Summary
                %s

                Why it matters
                %s

                Check next
                %s

                Source
                %s

                Disclaimer
                %s
                """.formatted(title, summary, whyItMatters, checkNext, firstNonBlank(originalLink, "-"), disclaimer).trim();
    }

    private String contentTypeForSource(SourceItem sourceItem) {
        String domain = firstNonBlank(sourceItem.getSourceDomain(), "SOCIAL_NEWS");
        return switch (domain) {
            case "EMPLOYMENT" -> "JOB_GUIDE";
            case "VISA_IMMIGRATION" -> "VISA_GUIDE";
            case "LIVING_INFO" -> "LIVING_TIP";
            case "COMMUNITY" -> "COMMUNITY_FAQ";
            default -> "NEWS_EXPLAINER";
        };
    }

    private BigDecimal qualityScore(SourceItem sourceItem) {
        if (!Boolean.TRUE.equals(sourceItem.getUsableForContentYn())) {
            return BigDecimal.valueOf(40);
        }
        return switch (firstNonBlank(sourceItem.getSourceRiskLevel(), "UNKNOWN")) {
            case "LOW" -> BigDecimal.valueOf(82);
            case "MEDIUM" -> BigDecimal.valueOf(72);
            default -> BigDecimal.valueOf(55);
        };
    }

    private BigDecimal riskScore(String sourceRiskLevel) {
        return switch (firstNonBlank(sourceRiskLevel, "UNKNOWN")) {
            case "LOW" -> BigDecimal.valueOf(20);
            case "MEDIUM" -> BigDecimal.valueOf(50);
            case "HIGH" -> BigDecimal.valueOf(80);
            default -> BigDecimal.valueOf(60);
        };
    }

    private String prefixIfMissing(String title, String prefix) {
        return title.toLowerCase().startsWith(prefix.toLowerCase()) ? title : prefix + ": " + title;
    }

    private String truncate(String value, int maxLength) {
        if (value == null || value.isBlank()) {
            return "";
        }
        String normalized = value.replaceAll("\\s+", " ").trim();
        return normalized.length() <= maxLength ? normalized : normalized.substring(0, maxLength) + "...";
    }

    private String firstNonBlank(String... values) {
        if (values == null) {
            return null;
        }
        for (String value : values) {
            if (value != null && !value.isBlank()) {
                return value.trim();
            }
        }
        return null;
    }
}
