CREATE SCHEMA IF NOT EXISTS content;
CREATE SCHEMA IF NOT EXISTS admin;

CREATE TABLE IF NOT EXISTS admin.module_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_key VARCHAR(120) NOT NULL UNIQUE,
    module_group VARCHAR(60) NOT NULL,
    module_name VARCHAR(120) NOT NULL,
    description TEXT,
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    run_order INTEGER NOT NULL DEFAULT 100,
    config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS content.content_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_domain VARCHAR(80) NOT NULL,
    content_type VARCHAR(80) NOT NULL,
    priority_group VARCHAR(80) NOT NULL DEFAULT 'NORMAL',
    category VARCHAR(120) NOT NULL DEFAULT '',
    title TEXT NOT NULL,
    summary_en TEXT NOT NULL DEFAULT '',
    why_it_matters_en TEXT NOT NULL DEFAULT '',
    body_en TEXT NOT NULL DEFAULT '',
    source_url TEXT NOT NULL DEFAULT '',
    source_name VARCHAR(200) NOT NULL DEFAULT '',
    original_source_url TEXT NOT NULL DEFAULT '',
    original_source_name VARCHAR(200) NOT NULL DEFAULT '',
    original_title TEXT NOT NULL DEFAULT '',
    original_published_at TIMESTAMPTZ,
    original_collected_at TIMESTAMPTZ,
    image_url TEXT NOT NULL DEFAULT '',
    link_url TEXT NOT NULL DEFAULT '',
    hashtags TEXT NOT NULL DEFAULT '',
    language VARCHAR(20) NOT NULL DEFAULT 'en',
    quality_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    relevance_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    practical_value_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    urgency_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    freshness_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    source_reliability_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    content_potential_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    rotation_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    final_publish_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    sensitive_yn BOOLEAN NOT NULL DEFAULT FALSE,
    review_required_yn BOOLEAN NOT NULL DEFAULT FALSE,
    review_reason TEXT NOT NULL DEFAULT '',
    status VARCHAR(40) NOT NULL DEFAULT 'RAW',
    publish_attempt_count INTEGER NOT NULL DEFAULT 0,
    last_publish_error TEXT NOT NULL DEFAULT '',
    next_retry_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    facebook_post_id VARCHAR(200) NOT NULL DEFAULT '',
    facebook_post_url TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content_created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    raw_ref_table VARCHAR(120) NOT NULL,
    raw_ref_id BIGINT NOT NULL,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ux_content_candidate_raw_ref UNIQUE(raw_ref_table, raw_ref_id),
    CONSTRAINT ck_content_candidate_status CHECK (
        status IN (
            'RAW', 'NORMALIZED', 'SUMMARIZED', 'SCORED',
            'READY_TO_REVIEW', 'READY_TO_PUBLISH', 'POSTED',
            'FAILED_RETRYABLE', 'POST_EXPIRED', 'ARCHIVED'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_content_candidate_status_score
ON content.content_candidate(status, final_publish_score DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_content_candidate_domain_type
ON content.content_candidate(source_domain, content_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_content_candidate_published
ON content.content_candidate(published_at DESC NULLS LAST);

CREATE INDEX IF NOT EXISTS idx_content_candidate_source_url
ON content.content_candidate(source_url);

ALTER TABLE content.content_candidate ADD COLUMN IF NOT EXISTS original_source_url TEXT NOT NULL DEFAULT '';
ALTER TABLE content.content_candidate ADD COLUMN IF NOT EXISTS original_source_name VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE content.content_candidate ADD COLUMN IF NOT EXISTS original_title TEXT NOT NULL DEFAULT '';
ALTER TABLE content.content_candidate ADD COLUMN IF NOT EXISTS original_published_at TIMESTAMPTZ;
ALTER TABLE content.content_candidate ADD COLUMN IF NOT EXISTS original_collected_at TIMESTAMPTZ;
ALTER TABLE content.content_candidate ADD COLUMN IF NOT EXISTS content_created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE content.content_candidate ADD COLUMN IF NOT EXISTS content_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE content.content_candidate
SET original_source_url = COALESCE(NULLIF(original_source_url, ''), source_url),
    original_source_name = COALESCE(NULLIF(original_source_name, ''), source_name),
    original_title = COALESCE(NULLIF(original_title, ''), title),
    original_collected_at = COALESCE(original_collected_at, NULLIF(raw_payload ->> 'collected_at', '')::timestamptz),
    original_published_at = COALESCE(original_published_at, NULLIF(raw_payload ->> 'original_published_at', '')::timestamptz),
    content_created_at = COALESCE(content_created_at, created_at),
    content_updated_at = COALESCE(content_updated_at, updated_at)
WHERE original_source_url = ''
   OR original_source_name = ''
   OR original_title = ''
   OR original_collected_at IS NULL
   OR content_created_at IS NULL
   OR content_updated_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_content_candidate_original_collected
ON content.content_candidate(original_collected_at DESC NULLS LAST, id DESC);

CREATE INDEX IF NOT EXISTS idx_content_candidate_content_updated
ON content.content_candidate(content_updated_at DESC NULLS LAST, id DESC);

CREATE TABLE IF NOT EXISTS content.publish_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_candidate_id BIGINT NOT NULL REFERENCES content.content_candidate(id) ON DELETE CASCADE,
    channel VARCHAR(40) NOT NULL DEFAULT 'facebook',
    status VARCHAR(40) NOT NULL,
    dry_run BOOLEAN NOT NULL DEFAULT TRUE,
    message_preview TEXT NOT NULL DEFAULT '',
    link_url TEXT NOT NULL DEFAULT '',
    facebook_post_id VARCHAR(200) NOT NULL DEFAULT '',
    facebook_post_url TEXT NOT NULL DEFAULT '',
    error_code VARCHAR(120) NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    request_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_content_publish_log_candidate
ON content.publish_log(content_candidate_id, created_at DESC);

INSERT INTO admin.module_config(module_key, module_group, module_name, description, is_enabled, is_required, run_order, config_json)
VALUES
    ('content.publisher', 'publisher', 'Content Publisher', 'Publish normalized content candidates to Facebook after source-specific collection pipelines sync into content.content_candidate.', TRUE, FALSE, 200, '{"interval_minutes":30,"direct_news_publish":false}'::jsonb),
    ('content.sync.social_news', 'content_sync', 'Social News Content Sync', 'Sync social_news.candidate rows into content.content_candidate.', TRUE, FALSE, 210, '{}'::jsonb),
    ('content.sync.immigration', 'content_sync', 'Immigration Notice Content Sync', 'Sync immigration_info.official_notice rows into content.content_candidate.', TRUE, FALSE, 220, '{}'::jsonb)
ON CONFLICT (module_key) DO UPDATE
SET module_name = EXCLUDED.module_name,
    description = EXCLUDED.description,
    config_json = admin.module_config.config_json || EXCLUDED.config_json,
    updated_at = CURRENT_TIMESTAMP;

UPDATE content.content_candidate
SET category = 'foreign_jobs',
    priority_group = 'PRIMARY',
    updated_at = CURRENT_TIMESTAMP,
    content_updated_at = CURRENT_TIMESTAMP
WHERE source_domain = 'SOCIAL_NEWS'
  AND category IN ('foreign_worker_news', 'jobs', 'foreign_worker_policy');

UPDATE content.content_candidate content_row
SET status = 'ARCHIVED',
    updated_at = CURRENT_TIMESTAMP,
    content_updated_at = CURRENT_TIMESTAMP,
    raw_payload = content_row.raw_payload || jsonb_build_object('archive_reason', 'non_representative_or_duplicate_social_news')
FROM social_news.candidate candidate
WHERE content_row.raw_ref_table = 'social_news.candidate'
  AND content_row.raw_ref_id = candidate.id
  AND (
      COALESCE(candidate.is_representative, TRUE) = FALSE
      OR COALESCE(candidate.publish_status, candidate.status, '') IN ('DUPLICATE', 'DUPLICATE_SKIPPED', 'SKIPPED', 'TEXT_INVALID', 'ARCHIVED')
      OR COALESCE(candidate.status, '') IN ('DUPLICATE', 'DUPLICATE_SKIPPED', 'SKIPPED', 'TEXT_INVALID', 'ARCHIVED')
  );

UPDATE content.content_candidate content_row
SET facebook_post_id = COALESCE(NULLIF(content_row.facebook_post_id, ''), news.facebook_post_id),
    facebook_post_url = COALESCE(NULLIF(content_row.facebook_post_url, ''), news.facebook_post_url),
    published_at = COALESCE(content_row.published_at, news.published_at),
    updated_at = CURRENT_TIMESTAMP,
    content_updated_at = CURRENT_TIMESTAMP
FROM social_news.candidate news
WHERE content_row.raw_ref_table = 'social_news.candidate'
  AND content_row.raw_ref_id = news.id
  AND (
      COALESCE(content_row.facebook_post_url, '') = ''
      OR content_row.published_at IS NULL
      OR COALESCE(content_row.facebook_post_id, '') = ''
  )
  AND (
      COALESCE(news.facebook_post_url, '') <> ''
      OR news.published_at IS NOT NULL
      OR COALESCE(news.facebook_post_id, '') <> ''
  );
