CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS social_news;

CREATE TABLE IF NOT EXISTS admin.module_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_key VARCHAR(120) NOT NULL UNIQUE,
    module_group VARCHAR(60) NOT NULL,
    module_name VARCHAR(120) NOT NULL,
    description TEXT,
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    run_order INTEGER NOT NULL DEFAULT 100,
    config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO admin.module_config(module_key, module_group, module_name, description, is_enabled, run_order)
VALUES
    ('social_news_bot', 'bot', '소셜 뉴스 봇', '뉴스 수집, 요약, 평가, 게시 자동화 런타임', TRUE, 10),
    ('job_collector_bot', 'bot', '채용정보 수집 봇', '고용24/워크넷 채용정보 수집 런타임', FALSE, 20)
ON CONFLICT (module_key) DO UPDATE
SET module_name = EXCLUDED.module_name,
    description = EXCLUDED.description,
    updated_at = CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS social_news.pipeline_cycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_key VARCHAR(80) NOT NULL UNIQUE,
    keyword VARCHAR(300) NOT NULL,
    dry_run BOOLEAN NOT NULL DEFAULT TRUE,
    requested_by VARCHAR(120),
    trigger_source VARCHAR(60) NOT NULL DEFAULT 'CLI',
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    enabled_modules JSONB NOT NULL DEFAULT '{}'::jsonb,
    collected_count INTEGER NOT NULL DEFAULT 0,
    saved_count INTEGER NOT NULL DEFAULT 0,
    duplicate_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    selected_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    compact_report TEXT,
    error_message TEXT
);

CREATE TABLE IF NOT EXISTS social_news.raw_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT,
    collector_module_key VARCHAR(120) NOT NULL DEFAULT 'social_news_bot',
    source_type VARCHAR(80) NOT NULL,
    source_url TEXT,
    google_news_url TEXT,
    source_name VARCHAR(200),
    publisher_name VARCHAR(200),
    search_keyword VARCHAR(300) NOT NULL DEFAULT '',
    raw_title TEXT NOT NULL,
    raw_summary TEXT,
    raw_content TEXT,
    language VARCHAR(20) NOT NULL DEFAULT 'ko',
    category VARCHAR(120),
    collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hash_key VARCHAR(128) NOT NULL,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_news_raw_item_hash ON social_news.raw_item(hash_key);

CREATE TABLE IF NOT EXISTS social_news.normalized_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_item_id BIGINT,
    cycle_id BIGINT,
    source_type VARCHAR(80) NOT NULL,
    source_url TEXT,
    canonical_url TEXT,
    google_news_url TEXT,
    source_name VARCHAR(200),
    publisher_name VARCHAR(200),
    title TEXT NOT NULL,
    summary TEXT,
    content TEXT,
    language VARCHAR(20) NOT NULL DEFAULT 'ko',
    category VARCHAR(120),
    keyword VARCHAR(300),
    hash_key VARCHAR(128) NOT NULL,
    title_hash VARCHAR(128),
    similarity_key VARCHAR(300),
    normalized_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_news_normalized_hash ON social_news.normalized_item(hash_key);

CREATE TABLE IF NOT EXISTS social_news.candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_item_id BIGINT,
    source_type VARCHAR(80) NOT NULL,
    source_url TEXT,
    canonical_url TEXT,
    google_news_url TEXT,
    source_name VARCHAR(200),
    publisher_name VARCHAR(200),
    title TEXT NOT NULL,
    summary TEXT,
    content TEXT,
    language VARCHAR(20) NOT NULL DEFAULT 'ko',
    category VARCHAR(120),
    keyword VARCHAR(300),
    hash_key VARCHAR(128),
    title_hash VARCHAR(128),
    similarity_key VARCHAR(300),
    short_summary TEXT,
    key_points TEXT,
    relevance_reason TEXT,
    risk_notes TEXT,
    generated_title TEXT,
    generated_summary_en TEXT,
    generated_why_it_matters_en TEXT,
    evaluation_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    duplicate_risk_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    foreign_worker_relevance_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    korea_relevance_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    visa_or_labor_policy_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    freshness_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    source_reliability_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    content_clarity_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    facebook_post_suitability_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    selection_reason TEXT,
    skip_reason TEXT,
    duplicate_group_id BIGINT,
    status VARCHAR(40) NOT NULL DEFAULT 'CANDIDATE',
    collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS facebook_post_url TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS facebook_post_id TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS last_publish_attempt_at TIMESTAMPTZ;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS publish_attempt_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS score_threshold NUMERIC(10,4) NOT NULL DEFAULT 0;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS score_breakdown_json TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS telegram_notified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS fail_reason TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS risk_level VARCHAR(30);
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS post_expired BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS post_expired_at TIMESTAMPTZ;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS post_expired_reason VARCHAR(100);
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS publish_cycle_id VARCHAR(10);
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS publish_status VARCHAR(50);
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS image_urls_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS canonical_url TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS google_news_url TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS publisher_name VARCHAR(200);
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS generated_title TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS generated_summary_en TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS generated_why_it_matters_en TEXT;

ALTER TABLE social_news.raw_item ADD COLUMN IF NOT EXISTS google_news_url TEXT;
ALTER TABLE social_news.raw_item ADD COLUMN IF NOT EXISTS publisher_name VARCHAR(200);
ALTER TABLE social_news.raw_item ADD COLUMN IF NOT EXISTS source_hash VARCHAR(128);
ALTER TABLE social_news.raw_item ADD COLUMN IF NOT EXISTS normalized_item_id BIGINT;
ALTER TABLE social_news.raw_item ADD COLUMN IF NOT EXISTS is_duplicate BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE social_news.raw_item ADD COLUMN IF NOT EXISTS duplicate_reason TEXT;
ALTER TABLE social_news.raw_item ADD COLUMN IF NOT EXISTS content_fetch_status VARCHAR(40);
ALTER TABLE social_news.raw_item ADD COLUMN IF NOT EXISTS content_fetch_error TEXT;
ALTER TABLE social_news.normalized_item ADD COLUMN IF NOT EXISTS canonical_url TEXT;
ALTER TABLE social_news.normalized_item ADD COLUMN IF NOT EXISTS google_news_url TEXT;
ALTER TABLE social_news.normalized_item ADD COLUMN IF NOT EXISTS publisher_name VARCHAR(200);
ALTER TABLE social_news.normalized_item ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE social_news.normalized_item ADD COLUMN IF NOT EXISTS image_urls_json JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE social_news.normalized_item ADD COLUMN IF NOT EXISTS raw_item_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE social_news.normalized_item ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
ALTER TABLE social_news.normalized_item ADD COLUMN IF NOT EXISTS content_fetch_status VARCHAR(40);
ALTER TABLE social_news.normalized_item ADD COLUMN IF NOT EXISTS content_fetch_error TEXT;

ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS related_source_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS duplicate_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS group_item_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS is_representative BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS representative_candidate_id BIGINT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS content_fetch_status VARCHAR(40);
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS content_fetch_error TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS content_category VARCHAR(80);
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS content_priority_group VARCHAR(20);
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS settlement_relevance_score NUMERIC(10,4) NOT NULL DEFAULT 0;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS practical_value_score NUMERIC(10,4) NOT NULL DEFAULT 0;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS category_rotation_score NUMERIC(10,4) NOT NULL DEFAULT 0;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS content_potential_score NUMERIC(10,4) NOT NULL DEFAULT 0;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS category_selection_reason TEXT;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS is_sensitive BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE social_news.candidate ADD COLUMN IF NOT EXISTS review_required_reason TEXT;

UPDATE social_news.candidate
SET content_category = COALESCE(NULLIF(content_category, ''), NULLIF(category, ''), 'foreign_worker_policy'),
    content_priority_group = COALESCE(NULLIF(content_priority_group, ''), 'PRIMARY')
WHERE content_category IS NULL
   OR content_category = ''
   OR content_priority_group IS NULL
   OR content_priority_group = '';

UPDATE social_news.candidate
SET category = 'foreign_jobs'
WHERE category IN ('foreign_worker_news', 'jobs', 'foreign_worker_policy');

UPDATE social_news.candidate
SET content_category = 'foreign_jobs',
    content_priority_group = 'PRIMARY'
WHERE content_category IN ('foreign_worker_news', 'jobs', 'foreign_worker_policy');

UPDATE social_news.raw_item
SET category = 'foreign_jobs'
WHERE category IN ('foreign_worker_news', 'jobs', 'foreign_worker_policy');

UPDATE social_news.normalized_item
SET category = 'foreign_jobs'
WHERE category IN ('foreign_worker_news', 'jobs', 'foreign_worker_policy');

WITH ranked_title_duplicates AS (
    SELECT
        id,
        FIRST_VALUE(id) OVER (
            PARTITION BY regexp_replace(lower(title), '[^0-9a-z가-힣]+', '', 'g')
            ORDER BY
                CASE
                    WHEN COALESCE(facebook_post_url, '') <> '' OR published_at IS NOT NULL THEN 0
                    WHEN publish_status = 'READY_TO_PUBLISH' THEN 1
                    ELSE 2
                END,
                evaluation_score DESC,
                id ASC
        ) AS representative_id,
        COUNT(*) OVER (PARTITION BY regexp_replace(lower(title), '[^0-9a-z가-힣]+', '', 'g')) AS duplicate_size
    FROM social_news.candidate
    WHERE length(regexp_replace(lower(title), '[^0-9a-z가-힣]+', '', 'g')) >= 18
)
UPDATE social_news.candidate candidate
SET duplicate_group_id = ranked.representative_id,
    representative_candidate_id = ranked.representative_id,
    is_representative = CASE WHEN candidate.id = ranked.representative_id THEN TRUE ELSE FALSE END,
    duplicate_count = GREATEST(candidate.duplicate_count, ranked.duplicate_size - 1),
    status = CASE
        WHEN candidate.id <> ranked.representative_id
         AND COALESCE(candidate.facebook_post_url, '') = ''
         AND candidate.published_at IS NULL
         AND candidate.status NOT IN ('POSTED', 'PUBLISHED', 'NOTIFIED', 'DRY_RUN_PUBLISHED', 'DRY_RUN_NOTIFIED', 'ARCHIVED')
        THEN 'DUPLICATE'
        ELSE candidate.status
    END,
    publish_status = CASE
        WHEN candidate.id <> ranked.representative_id
         AND COALESCE(candidate.facebook_post_url, '') = ''
         AND candidate.published_at IS NULL
         AND candidate.publish_status NOT IN ('POSTED', 'PUBLISHED', 'NOTIFIED', 'DRY_RUN_PUBLISHED', 'DRY_RUN_NOTIFIED', 'ARCHIVED')
        THEN 'DUPLICATE'
        ELSE candidate.publish_status
    END,
    skip_reason = CASE
        WHEN candidate.id <> ranked.representative_id
         AND COALESCE(candidate.facebook_post_url, '') = ''
         AND candidate.published_at IS NULL
        THEN 'Duplicate title/content candidate; source was ignored for duplicate grouping.'
        ELSE candidate.skip_reason
    END,
    updated_at = CURRENT_TIMESTAMP
FROM ranked_title_duplicates ranked
WHERE candidate.id = ranked.id
  AND ranked.duplicate_size > 1;

ALTER TABLE social_news.candidate ALTER COLUMN evaluation_score TYPE NUMERIC(10,4);
ALTER TABLE social_news.candidate ALTER COLUMN duplicate_risk_score TYPE NUMERIC(10,4);
ALTER TABLE social_news.candidate ALTER COLUMN foreign_worker_relevance_score TYPE NUMERIC(10,4);
ALTER TABLE social_news.candidate ALTER COLUMN korea_relevance_score TYPE NUMERIC(10,4);
ALTER TABLE social_news.candidate ALTER COLUMN visa_or_labor_policy_score TYPE NUMERIC(10,4);
ALTER TABLE social_news.candidate ALTER COLUMN freshness_score TYPE NUMERIC(10,4);
ALTER TABLE social_news.candidate ALTER COLUMN source_reliability_score TYPE NUMERIC(10,4);
ALTER TABLE social_news.candidate ALTER COLUMN content_clarity_score TYPE NUMERIC(10,4);
ALTER TABLE social_news.candidate ALTER COLUMN facebook_post_suitability_score TYPE NUMERIC(10,4);
ALTER TABLE social_news.candidate ALTER COLUMN score_threshold TYPE NUMERIC(10,4);

DROP INDEX IF EXISTS social_news.ux_news_raw_item_hash;
CREATE INDEX IF NOT EXISTS idx_news_raw_item_hash ON social_news.raw_item(hash_key);
CREATE INDEX IF NOT EXISTS idx_news_raw_item_source_hash ON social_news.raw_item(source_hash);
CREATE INDEX IF NOT EXISTS idx_news_raw_item_normalized ON social_news.raw_item(normalized_item_id);
CREATE INDEX IF NOT EXISTS idx_news_candidate_normalized ON social_news.candidate(normalized_item_id);
CREATE INDEX IF NOT EXISTS idx_news_candidate_representative ON social_news.candidate(is_representative, collected_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_news_candidate_representative_id ON social_news.candidate(representative_candidate_id);
CREATE INDEX IF NOT EXISTS idx_news_candidate_content_group ON social_news.candidate(content_priority_group, content_category, collected_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_candidate_sensitive ON social_news.candidate(is_sensitive, publish_status, collected_at DESC);

UPDATE social_news.raw_item
SET source_hash = COALESCE(raw_payload ->> 'hash_key', source_hash, hash_key)
WHERE source_hash IS NULL;

UPDATE social_news.raw_item raw
SET normalized_item_id = normalized.id
FROM social_news.normalized_item normalized
WHERE raw.normalized_item_id IS NULL
  AND normalized.hash_key = raw.source_hash;

UPDATE social_news.normalized_item normalized
SET raw_item_count = stats.raw_count,
    last_seen_at = stats.last_seen_at
FROM (
    SELECT normalized_item_id, COUNT(*)::int AS raw_count, MAX(collected_at) AS last_seen_at
    FROM social_news.raw_item
    WHERE normalized_item_id IS NOT NULL
    GROUP BY normalized_item_id
) stats
WHERE normalized.id = stats.normalized_item_id;

WITH ranked AS (
    SELECT
        id,
        normalized_item_id,
        ROW_NUMBER() OVER (PARTITION BY normalized_item_id ORDER BY id ASC) AS rn
    FROM social_news.candidate
    WHERE normalized_item_id IS NOT NULL
),
grouped AS (
    SELECT
        candidate.normalized_item_id,
        COUNT(*)::int AS group_count,
        MAX(candidate.collected_at) AS last_seen_at,
        COUNT(DISTINCT COALESCE(NULLIF(candidate.source_name, ''), candidate.source_url))::int AS related_count,
        MIN(candidate.id) AS representative_id
    FROM social_news.candidate candidate
    WHERE candidate.normalized_item_id IS NOT NULL
    GROUP BY candidate.normalized_item_id
)
UPDATE social_news.candidate candidate
SET is_representative = ranked.rn = 1,
    group_item_count = grouped.group_count,
    duplicate_count = GREATEST(grouped.group_count - 1, 0),
    related_source_count = GREATEST(grouped.related_count, 1),
    last_seen_at = grouped.last_seen_at,
    duplicate_group_id = grouped.representative_id,
    representative_candidate_id = grouped.representative_id
FROM ranked
JOIN grouped ON grouped.normalized_item_id = ranked.normalized_item_id
WHERE candidate.id = ranked.id;

UPDATE social_news.candidate
SET representative_candidate_id = id
WHERE representative_candidate_id IS NULL
  AND COALESCE(is_representative, TRUE) = TRUE;

WITH ranked_title_duplicates AS (
    SELECT
        id,
        FIRST_VALUE(id) OVER (
            PARTITION BY regexp_replace(lower(title), '[^0-9a-z가-힣]+', '', 'g')
            ORDER BY
                CASE
                    WHEN COALESCE(facebook_post_url, '') <> '' OR published_at IS NOT NULL THEN 0
                    WHEN publish_status = 'READY_TO_PUBLISH' THEN 1
                    ELSE 2
                END,
                evaluation_score DESC,
                id ASC
        ) AS representative_id,
        COUNT(*) OVER (PARTITION BY regexp_replace(lower(title), '[^0-9a-z가-힣]+', '', 'g')) AS duplicate_size
    FROM social_news.candidate
    WHERE length(regexp_replace(lower(title), '[^0-9a-z가-힣]+', '', 'g')) >= 18
)
UPDATE social_news.candidate candidate
SET duplicate_group_id = ranked.representative_id,
    representative_candidate_id = ranked.representative_id,
    is_representative = CASE WHEN candidate.id = ranked.representative_id THEN TRUE ELSE FALSE END,
    duplicate_count = GREATEST(candidate.duplicate_count, ranked.duplicate_size - 1),
    status = CASE
        WHEN candidate.id <> ranked.representative_id
         AND COALESCE(candidate.facebook_post_url, '') = ''
         AND candidate.published_at IS NULL
         AND candidate.status NOT IN ('POSTED', 'PUBLISHED', 'NOTIFIED', 'DRY_RUN_PUBLISHED', 'DRY_RUN_NOTIFIED', 'ARCHIVED')
        THEN 'DUPLICATE'
        ELSE candidate.status
    END,
    publish_status = CASE
        WHEN candidate.id <> ranked.representative_id
         AND COALESCE(candidate.facebook_post_url, '') = ''
         AND candidate.published_at IS NULL
         AND candidate.publish_status NOT IN ('POSTED', 'PUBLISHED', 'NOTIFIED', 'DRY_RUN_PUBLISHED', 'DRY_RUN_NOTIFIED', 'ARCHIVED')
        THEN 'DUPLICATE'
        ELSE candidate.publish_status
    END,
    skip_reason = CASE
        WHEN candidate.id <> ranked.representative_id
         AND COALESCE(candidate.facebook_post_url, '') = ''
         AND candidate.published_at IS NULL
        THEN 'Duplicate title/content candidate; source was ignored for duplicate grouping.'
        ELSE candidate.skip_reason
    END,
    updated_at = CURRENT_TIMESTAMP
FROM ranked_title_duplicates ranked
WHERE candidate.id = ranked.id
  AND ranked.duplicate_size > 1;

CREATE INDEX IF NOT EXISTS idx_news_candidate_publish_cycle
ON social_news.candidate(publish_cycle_id, publish_status, post_expired, published_at);

CREATE TABLE IF NOT EXISTS social_news.pipeline_step_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    module_key VARCHAR(120) NOT NULL DEFAULT 'social_news_bot',
    step_name VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    input_count INTEGER NOT NULL DEFAULT 0,
    output_count INTEGER NOT NULL DEFAULT 0,
    skipped_reason TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    duration_ms INTEGER,
    detail_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE social_news.pipeline_step_log ADD COLUMN IF NOT EXISTS news_candidate_id BIGINT;
ALTER TABLE social_news.pipeline_step_log ADD COLUMN IF NOT EXISTS message TEXT;
ALTER TABLE social_news.pipeline_step_log ADD COLUMN IF NOT EXISTS payload_json JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE social_news.pipeline_step_log ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_news_pipeline_step_created
ON social_news.pipeline_step_log(created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS social_news.publish_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT,
    news_candidate_id BIGINT NOT NULL,
    channel VARCHAR(60) NOT NULL DEFAULT 'facebook',
    page_id VARCHAR(200),
    external_post_id VARCHAR(200),
    dry_run BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(40) NOT NULL,
    request_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_code VARCHAR(80),
    error_message TEXT,
    published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE social_news.publish_log ADD COLUMN IF NOT EXISTS facebook_permalink TEXT;
ALTER TABLE social_news.publish_log ADD COLUMN IF NOT EXISTS score NUMERIC(10,4) NOT NULL DEFAULT 0;
ALTER TABLE social_news.publish_log ADD COLUMN IF NOT EXISTS threshold NUMERIC(10,4) NOT NULL DEFAULT 0;
ALTER TABLE social_news.publish_log ADD COLUMN IF NOT EXISTS message_preview TEXT;
ALTER TABLE social_news.publish_log ADD COLUMN IF NOT EXISTS response_code TEXT;
ALTER TABLE social_news.publish_log ADD COLUMN IF NOT EXISTS response_body TEXT;

CREATE TABLE IF NOT EXISTS social_news.telegram_notify_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT,
    news_candidate_id BIGINT,
    chat_id_ref VARCHAR(120),
    dry_run BOOLEAN NOT NULL DEFAULT TRUE,
    message TEXT NOT NULL,
    status VARCHAR(40) NOT NULL,
    error_message TEXT,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin.employment_job_posting (
    wanted_auth_no TEXT PRIMARY KEY,
    company TEXT,
    busino TEXT,
    ind_tp_nm TEXT,
    title TEXT,
    sal_tp_nm TEXT,
    sal TEXT,
    min_sal TEXT,
    max_sal TEXT,
    region TEXT,
    holiday_tp_nm TEXT,
    min_edubg TEXT,
    max_edubg TEXT,
    career TEXT,
    reg_dt TEXT,
    close_dt TEXT,
    info_svc TEXT,
    wanted_info_url TEXT,
    wanted_mobile_info_url TEXT,
    zip_cd TEXT,
    strtnm_cd TEXT,
    basic_addr TEXT,
    detail_addr TEXT,
    emp_tp_cd TEXT,
    jobs_cd TEXT,
    smodify_dtm TEXT,
    raw_xml TEXT,
    collected_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin.employment_job_collector_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    page_from INTEGER NOT NULL,
    page_to INTEGER NOT NULL,
    display INTEGER NOT NULL,
    sort_order_by TEXT NOT NULL,
    total_received INTEGER NOT NULL DEFAULT 0,
    inserted_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    failed_pages_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    status TEXT NOT NULL,
    error_message TEXT,
    request_params_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin.employment_job_collector_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    display INTEGER NOT NULL DEFAULT 100,
    start_page_from INTEGER NOT NULL DEFAULT 1,
    start_page_to INTEGER NOT NULL DEFAULT 10,
    sort_order_by TEXT NOT NULL DEFAULT 'DESC',
    interval_minutes INTEGER NOT NULL DEFAULT 60,
    filter_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    scheduler_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    scheduler_started_at TIMESTAMPTZ,
    scheduler_stopped_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE admin.employment_job_collector_settings ADD COLUMN IF NOT EXISTS scheduler_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE admin.employment_job_collector_settings ADD COLUMN IF NOT EXISTS scheduler_started_at TIMESTAMPTZ;
ALTER TABLE admin.employment_job_collector_settings ADD COLUMN IF NOT EXISTS scheduler_stopped_at TIMESTAMPTZ;

INSERT INTO admin.employment_job_collector_settings
    (id, display, start_page_from, start_page_to, sort_order_by, interval_minutes, filter_enabled, scheduler_enabled)
VALUES (1, 100, 1, 10, 'DESC', 60, FALSE, FALSE)
ON CONFLICT (id) DO NOTHING;
