CREATE SCHEMA IF NOT EXISTS immigration_info;

CREATE TABLE IF NOT EXISTS immigration_info.official_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(80) NOT NULL,
    source_name VARCHAR(200) NOT NULL,
    source_type VARCHAR(60) NOT NULL,
    notice_type VARCHAR(60) NOT NULL,
    title_ko TEXT NOT NULL,
    title_en TEXT,
    original_url TEXT NOT NULL,
    canonical_url TEXT NOT NULL,
    published_at TIMESTAMPTZ,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    raw_content_ko TEXT,
    raw_content_en TEXT,
    summary_en TEXT,
    why_it_matters_en TEXT,
    affected_visa_types JSONB NOT NULL DEFAULT '[]'::jsonb,
    affected_user_groups JSONB NOT NULL DEFAULT '[]'::jsonb,
    region_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    policy_keywords JSONB NOT NULL DEFAULT '[]'::jsonb,
    importance_score NUMERIC(8, 4) NOT NULL DEFAULT 0,
    urgency_level VARCHAR(20) NOT NULL DEFAULT 'LOW',
    content_status VARCHAR(40) NOT NULL DEFAULT 'RAW_COLLECTED',
    active_yn CHAR(1) NOT NULL DEFAULT 'Y',
    duplicate_group_id BIGINT,
    raw_response JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (canonical_url)
);

CREATE INDEX IF NOT EXISTS idx_immigration_notice_source_type ON immigration_info.official_notice(source_type);
CREATE INDEX IF NOT EXISTS idx_immigration_notice_notice_type ON immigration_info.official_notice(notice_type);
CREATE INDEX IF NOT EXISTS idx_immigration_notice_status ON immigration_info.official_notice(content_status);
CREATE INDEX IF NOT EXISTS idx_immigration_notice_published_at ON immigration_info.official_notice(published_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_immigration_notice_importance ON immigration_info.official_notice(importance_score DESC);
CREATE INDEX IF NOT EXISTS idx_immigration_notice_visa_gin ON immigration_info.official_notice USING GIN(affected_visa_types);

CREATE TABLE IF NOT EXISTS immigration_info.collect_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collector_type VARCHAR(120) NOT NULL,
    source_name VARCHAR(200) NOT NULL,
    status VARCHAR(40) NOT NULL,
    requested_count INTEGER NOT NULL DEFAULT 0,
    inserted_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    error_message TEXT,
    request_params JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_immigration_collect_log_started_at ON immigration_info.collect_log(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_immigration_collect_log_status ON immigration_info.collect_log(status);

CREATE TABLE IF NOT EXISTS immigration_info.publish_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id BIGINT NOT NULL REFERENCES immigration_info.official_notice(id) ON DELETE CASCADE,
    facebook_post_id VARCHAR(200),
    facebook_post_url TEXT,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    error_message TEXT,
    posted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_immigration_publish_log_notice ON immigration_info.publish_log(notice_id);
CREATE INDEX IF NOT EXISTS idx_immigration_publish_log_status ON immigration_info.publish_log(status);

INSERT INTO admin.module_config(module_key, module_group, module_name, description, is_enabled, run_order, config_json)
VALUES
    ('immigration_notice_bot', 'bot', '출입국 공지 수집 봇', '법무부, 하이코리아, EPS 등 공식 출처의 비자/체류/외국인 정책 공지를 수집합니다.', TRUE, 30, '{"auto_publish":false}'::jsonb)
ON CONFLICT (module_key) DO UPDATE
SET module_name = EXCLUDED.module_name,
    description = EXCLUDED.description,
    is_enabled = EXCLUDED.is_enabled,
    updated_at = CURRENT_TIMESTAMP;
