CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS social_news;

CREATE TABLE IF NOT EXISTS admin.module_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_key VARCHAR(120) NOT NULL UNIQUE,
    module_group VARCHAR(60) NOT NULL,
    module_name VARCHAR(120) NOT NULL,
    description TEXT,
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    run_order INTEGER NOT NULL DEFAULT 100,
    config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_module_config_group
ON admin.module_config(module_group, is_enabled, run_order);

CREATE TABLE IF NOT EXISTS admin.runtime_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(120) NOT NULL UNIQUE,
    config_value TEXT,
    value_type VARCHAR(30) NOT NULL DEFAULT 'string',
    is_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    updated_by VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin.env_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    env_key VARCHAR(120) NOT NULL UNIQUE,
    module_key VARCHAR(120),
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    is_configured BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    checked_at TIMESTAMPTZ,
    message TEXT,
    CONSTRAINT fk_admin_env_status_module
        FOREIGN KEY(module_key) REFERENCES admin.module_config(module_key)
);

CREATE INDEX IF NOT EXISTS idx_admin_env_status_module
ON admin.env_status(module_key, status);

CREATE TABLE IF NOT EXISTS admin.admin_login_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(120) NOT NULL,
    ip_address VARCHAR(80) NOT NULL,
    user_agent TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    telegram_message_id BIGINT,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMPTZ,
    rejected_at TIMESTAMPTZ,
    logged_out_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_admin_login_session_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'LOGGED_OUT'))
);

CREATE INDEX IF NOT EXISTS idx_admin_login_session_lookup
ON admin.admin_login_session(device_id, ip_address, left(user_agent, 180), status);

CREATE UNIQUE INDEX IF NOT EXISTS ux_admin_login_session_approved_active
ON admin.admin_login_session(device_id, ip_address, user_agent)
WHERE status = 'APPROVED';

CREATE UNIQUE INDEX IF NOT EXISTS ux_admin_login_session_pending_active
ON admin.admin_login_session(device_id, ip_address, user_agent)
WHERE status = 'PENDING';

CREATE TABLE IF NOT EXISTS social_news.pipeline_cycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_key VARCHAR(80) NOT NULL UNIQUE,
    keyword VARCHAR(300) NOT NULL,
    dry_run BOOLEAN NOT NULL DEFAULT TRUE,
    requested_by VARCHAR(120),
    trigger_source VARCHAR(60) NOT NULL DEFAULT 'CLI',
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    enabled_modules JSONB NOT NULL DEFAULT '{}'::jsonb,
    collected_count INTEGER NOT NULL DEFAULT 0,
    saved_count INTEGER NOT NULL DEFAULT 0,
    duplicate_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    selected_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    compact_report TEXT,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_news_pipeline_cycle_started
ON social_news.pipeline_cycle(started_at DESC);

CREATE INDEX IF NOT EXISTS idx_news_pipeline_cycle_status
ON social_news.pipeline_cycle(status, dry_run);

CREATE TABLE IF NOT EXISTS social_news.pipeline_step_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL,
    module_key VARCHAR(120) NOT NULL,
    step_name VARCHAR(120) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
    input_count INTEGER NOT NULL DEFAULT 0,
    output_count INTEGER NOT NULL DEFAULT 0,
    skipped_reason TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    duration_ms INTEGER,
    detail_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_news_pipeline_step_cycle
        FOREIGN KEY(cycle_id) REFERENCES social_news.pipeline_cycle(id),
    CONSTRAINT fk_news_pipeline_step_module
        FOREIGN KEY(module_key) REFERENCES admin.module_config(module_key)
);

CREATE INDEX IF NOT EXISTS idx_news_pipeline_step_cycle
ON social_news.pipeline_step_log(cycle_id, started_at);

CREATE INDEX IF NOT EXISTS idx_news_pipeline_step_module
ON social_news.pipeline_step_log(module_key, status);

CREATE TABLE IF NOT EXISTS social_news.pipeline_error_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT,
    step_log_id BIGINT,
    module_key VARCHAR(120),
    severity VARCHAR(30) NOT NULL DEFAULT 'ERROR',
    error_code VARCHAR(80),
    error_message TEXT NOT NULL,
    stack_trace TEXT,
    context_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_news_pipeline_error_cycle
        FOREIGN KEY(cycle_id) REFERENCES social_news.pipeline_cycle(id),
    CONSTRAINT fk_news_pipeline_error_step
        FOREIGN KEY(step_log_id) REFERENCES social_news.pipeline_step_log(id),
    CONSTRAINT fk_news_pipeline_error_module
        FOREIGN KEY(module_key) REFERENCES admin.module_config(module_key)
);

CREATE INDEX IF NOT EXISTS idx_news_pipeline_error_cycle
ON social_news.pipeline_error_log(cycle_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS social_news.raw_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT,
    collector_module_key VARCHAR(120) NOT NULL,
    source_type VARCHAR(80) NOT NULL,
    source_url TEXT,
    source_name VARCHAR(200),
    search_keyword VARCHAR(300) NOT NULL,
    raw_title TEXT NOT NULL,
    raw_summary TEXT,
    raw_content TEXT,
    language VARCHAR(20) NOT NULL DEFAULT 'ko',
    category VARCHAR(120),
    collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hash_key VARCHAR(128) NOT NULL,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_news_raw_cycle
        FOREIGN KEY(cycle_id) REFERENCES social_news.pipeline_cycle(id),
    CONSTRAINT fk_news_raw_collector
        FOREIGN KEY(collector_module_key) REFERENCES admin.module_config(module_key)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_news_raw_item_hash
ON social_news.raw_item(hash_key);

CREATE INDEX IF NOT EXISTS idx_news_raw_cycle
ON social_news.raw_item(cycle_id, collector_module_key);

CREATE TABLE IF NOT EXISTS social_news.normalized_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_item_id BIGINT,
    cycle_id BIGINT,
    source_type VARCHAR(80) NOT NULL,
    source_url TEXT,
    canonical_url TEXT,
    source_name VARCHAR(200),
    title TEXT NOT NULL,
    summary TEXT,
    content TEXT,
    language VARCHAR(20) NOT NULL DEFAULT 'ko',
    category VARCHAR(120),
    keyword VARCHAR(300),
    hash_key VARCHAR(128) NOT NULL,
    title_hash VARCHAR(128),
    similarity_key VARCHAR(300),
    normalized_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_news_normalized_raw
        FOREIGN KEY(raw_item_id) REFERENCES social_news.raw_item(id),
    CONSTRAINT fk_news_normalized_cycle
        FOREIGN KEY(cycle_id) REFERENCES social_news.pipeline_cycle(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_news_normalized_hash
ON social_news.normalized_item(hash_key);

CREATE INDEX IF NOT EXISTS idx_news_normalized_similarity
ON social_news.normalized_item(similarity_key);

CREATE TABLE IF NOT EXISTS social_news.candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_item_id BIGINT,
    cycle_id BIGINT,
    source_type VARCHAR(80) NOT NULL,
    source_url TEXT,
    canonical_url TEXT,
    source_name VARCHAR(200),
    title TEXT NOT NULL,
    summary TEXT,
    content TEXT,
    language VARCHAR(20) NOT NULL DEFAULT 'ko',
    category VARCHAR(120),
    keyword VARCHAR(300),
    hash_key VARCHAR(128),
    title_hash VARCHAR(128),
    similarity_key VARCHAR(300),
    short_summary TEXT,
    key_points TEXT,
    relevance_reason TEXT,
    risk_notes TEXT,
    evaluation_score NUMERIC(6,4) NOT NULL DEFAULT 0,
    duplicate_risk_score NUMERIC(6,4) NOT NULL DEFAULT 0,
    foreign_worker_relevance_score NUMERIC(6,4) NOT NULL DEFAULT 0,
    korea_relevance_score NUMERIC(6,4) NOT NULL DEFAULT 0,
    visa_or_labor_policy_score NUMERIC(6,4) NOT NULL DEFAULT 0,
    freshness_score NUMERIC(6,4) NOT NULL DEFAULT 0,
    source_reliability_score NUMERIC(6,4) NOT NULL DEFAULT 0,
    content_clarity_score NUMERIC(6,4) NOT NULL DEFAULT 0,
    facebook_post_suitability_score NUMERIC(6,4) NOT NULL DEFAULT 0,
    selection_reason TEXT,
    skip_reason TEXT,
    duplicate_group_id BIGINT,
    status VARCHAR(40) NOT NULL DEFAULT 'CANDIDATE',
    collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_news_candidate_normalized
        FOREIGN KEY(normalized_item_id) REFERENCES social_news.normalized_item(id),
    CONSTRAINT fk_news_candidate_cycle
        FOREIGN KEY(cycle_id) REFERENCES social_news.pipeline_cycle(id),
    CONSTRAINT fk_news_candidate_duplicate_group
        FOREIGN KEY(duplicate_group_id) REFERENCES social_news.candidate(id)
);

CREATE INDEX IF NOT EXISTS idx_news_candidate_cycle_status
ON social_news.candidate(cycle_id, status);

CREATE INDEX IF NOT EXISTS idx_news_candidate_score
ON social_news.candidate(evaluation_score DESC);

CREATE INDEX IF NOT EXISTS idx_news_candidate_hash
ON social_news.candidate(hash_key);

CREATE INDEX IF NOT EXISTS idx_news_candidate_similarity
ON social_news.candidate(similarity_key);

CREATE TABLE IF NOT EXISTS social_news.publish_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT,
    news_candidate_id BIGINT NOT NULL,
    channel VARCHAR(60) NOT NULL DEFAULT 'facebook',
    page_id VARCHAR(200),
    external_post_id VARCHAR(200),
    dry_run BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(40) NOT NULL,
    request_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    response_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_code VARCHAR(80),
    error_message TEXT,
    published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_social_publish_cycle
        FOREIGN KEY(cycle_id) REFERENCES social_news.pipeline_cycle(id),
    CONSTRAINT fk_social_publish_candidate
        FOREIGN KEY(news_candidate_id) REFERENCES social_news.candidate(id)
);

CREATE INDEX IF NOT EXISTS idx_social_publish_candidate
ON social_news.publish_log(news_candidate_id, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_publish_status
ON social_news.publish_log(channel, status, dry_run);

CREATE TABLE IF NOT EXISTS social_news.telegram_notify_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT,
    news_candidate_id BIGINT,
    chat_id_ref VARCHAR(120),
    dry_run BOOLEAN NOT NULL DEFAULT TRUE,
    message TEXT NOT NULL,
    status VARCHAR(40) NOT NULL,
    error_message TEXT,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_telegram_notify_cycle
        FOREIGN KEY(cycle_id) REFERENCES social_news.pipeline_cycle(id),
    CONSTRAINT fk_telegram_notify_candidate
        FOREIGN KEY(news_candidate_id) REFERENCES social_news.candidate(id)
);

CREATE INDEX IF NOT EXISTS idx_telegram_notify_candidate
ON social_news.telegram_notify_log(news_candidate_id, sent_at DESC);

CREATE INDEX IF NOT EXISTS idx_telegram_notify_status
ON social_news.telegram_notify_log(status, dry_run);
