"""Admin API for the Vue dashboard with Telegram approval auth."""

from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import json
import os
import threading
import time
from http import cookies
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


DEFAULT_DSN = "postgresql://postgres@localhost:5432/foreign_worker_job_info"
SESSION_COOKIE = "workconnect_admin_session"
APPROVED = "APPROVED"
PENDING = "PENDING"
REJECTED = "REJECTED"
LOGGED_OUT = "LOGGED_OUT"
PENDING_TIMEOUT_MINUTES = 3
PUBLIC_POST_PATHS = {"/api/admin/auth/check", "/api/admin/auth/logout", "/api/admin/telegram/callback"}
PUBLIC_GET_PREFIXES = ("/api/admin/auth/status/",)
PUBLIC_GET_PATHS = {"/api/health"}
ALLOWED_ADMIN_ORIGINS = {
    "http://127.0.0.1:5173",
    "http://localhost:5173",
}


def load_env_file() -> None:
    candidates = [
        Path.cwd() / ".env",
        Path(__file__).resolve().parents[1] / ".env",
    ]
    for env_path in candidates:
        if not env_path.exists():
            continue
        for raw_line in env_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


def build_dsn() -> str:
    explicit = os.environ.get("POSTGRES_DSN")
    if explicit:
        return explicit

    host = os.environ.get("PGHOST", "localhost")
    port = os.environ.get("PGPORT", "5432")
    database = os.environ.get("PGDATABASE", "foreign_worker_job_info")
    user = os.environ.get("PGUSER", "postgres")
    password = os.environ.get("PGPASSWORD")
    if password:
        return f"postgresql://{user}:{password}@{host}:{port}/{database}"
    return f"postgresql://{user}@{host}:{port}/{database}"


def connect():
    try:
        import psycopg  # type: ignore
    except ImportError as exc:
        raise RuntimeError("관리자 API 실행에 필요한 psycopg 패키지가 설치되어 있지 않습니다.") from exc

    return psycopg.connect(build_dsn())


def ensure_auth_schema() -> None:
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE SCHEMA IF NOT EXISTS admin;

                CREATE TABLE IF NOT EXISTS admin.admin_login_session (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    device_id VARCHAR(120) NOT NULL,
                    ip_address VARCHAR(80) NOT NULL,
                    user_agent TEXT NOT NULL,
                    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
                    telegram_message_id BIGINT,
                    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    approved_at TIMESTAMPTZ,
                    rejected_at TIMESTAMPTZ,
                    logged_out_at TIMESTAMPTZ,
                    last_seen_at TIMESTAMPTZ,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ck_admin_login_session_status
                        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'LOGGED_OUT'))
                );

                CREATE INDEX IF NOT EXISTS idx_admin_login_session_lookup
                ON admin.admin_login_session(device_id, ip_address, left(user_agent, 180), status);

                CREATE UNIQUE INDEX IF NOT EXISTS ux_admin_login_session_approved_active
                ON admin.admin_login_session(device_id, ip_address, user_agent)
                WHERE status = 'APPROVED';

                CREATE UNIQUE INDEX IF NOT EXISTS ux_admin_login_session_pending_active
                ON admin.admin_login_session(device_id, ip_address, user_agent)
                WHERE status = 'PENDING';
                """
            )
        conn.commit()


def fetch_all(sql: str, params: tuple[Any, ...] = ()) -> list[dict[str, Any]]:
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            columns = [column.name for column in cur.description]
            return [dict(zip(columns, row)) for row in cur.fetchall()]


def fetch_one(sql: str, params: tuple[Any, ...] = ()) -> dict[str, Any]:
    rows = fetch_all(sql, params)
    return rows[0] if rows else {}


def execute_one(sql: str, params: tuple[Any, ...] = ()) -> dict[str, Any]:
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            row = cur.fetchone()
            columns = [column.name for column in cur.description] if cur.description else []
        conn.commit()
    return dict(zip(columns, row)) if row else {}


def json_ready(value: Any) -> Any:
    if isinstance(value, list):
        return [json_ready(item) for item in value]
    if isinstance(value, dict):
        return {key: json_ready(item) for key, item in value.items()}
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return value


def client_ip(handler: BaseHTTPRequestHandler) -> str:
    forwarded = handler.headers.get("X-Forwarded-For", "").split(",")[0].strip()
    if forwarded:
        return forwarded
    real_ip = handler.headers.get("X-Real-IP", "").strip()
    if real_ip:
        return real_ip
    return handler.client_address[0]


def callback_secret() -> str:
    return (
        os.environ.get("ADMIN_TELEGRAM_CALLBACK_TOKEN", "").strip()
        or os.environ.get("TELEGRAM_WEBHOOK_SECRET", "").strip()
        or os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
    )


def callback_signature(session_id: int, action: str) -> str:
    secret = callback_secret()
    if not secret:
        return ""
    digest = hmac.new(secret.encode("utf-8"), f"{session_id}:{action}".encode("utf-8"), hashlib.sha256).digest()
    return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")[:24]


def build_callback_data(session_id: int, action: str) -> str:
    return f"admin_auth:{action}:{session_id}:{callback_signature(session_id, action)}"


def parse_callback_data(data: str) -> tuple[str, int, str] | None:
    parts = data.split(":")
    if len(parts) != 4 or parts[0] != "admin_auth":
        return None
    action = parts[1]
    if action not in {"approve", "reject"}:
        return None
    try:
        session_id = int(parts[2])
    except ValueError:
        return None
    return action, session_id, parts[3]


def verify_callback_secret(handler: BaseHTTPRequestHandler, parsed_url) -> bool:
    secret = os.environ.get("ADMIN_TELEGRAM_CALLBACK_TOKEN", "").strip() or os.environ.get("TELEGRAM_WEBHOOK_SECRET", "").strip()
    if not secret:
        return True
    query_token = parse_qs(parsed_url.query).get("token", [""])[0]
    header_token = handler.headers.get("X-Telegram-Bot-Api-Secret-Token", "") or handler.headers.get("X-Admin-Telegram-Secret", "")
    return hmac.compare_digest(secret, query_token) or hmac.compare_digest(secret, header_token)


def telegram_api(method: str, payload: dict[str, Any]) -> dict[str, Any]:
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
    if not token:
        return {"ok": False, "description": "Telegram Bot Token이 설정되어 있지 않습니다."}
    request = Request(
        f"https://api.telegram.org/bot{token}/{method}",
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(request, timeout=15) as response:
            return json.loads(response.read().decode("utf-8", errors="replace"))
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        try:
            payload = json.loads(detail)
            return {"ok": False, "description": payload.get("description") or "Telegram 요청 전송에 실패했습니다."}
        except json.JSONDecodeError:
            return {"ok": False, "description": f"Telegram 요청 전송에 실패했습니다. HTTP {exc.code}"}
    except URLError:
        return {"ok": False, "description": "Telegram 서버에 연결할 수 없습니다."}
    except Exception:
        return {"ok": False, "description": "Telegram 요청 전송에 실패했습니다."}


def telegram_admin_chat_id() -> str:
    return os.environ.get("TELEGRAM_OWNER_CHAT_ID", "").strip() or os.environ.get("TELEGRAM_CHAT_ID", "").strip()


def telegram_owner_user_id() -> str:
    return os.environ.get("TELEGRAM_OWNER_USER_ID", "").strip()


def send_approval_request(session: dict[str, Any]) -> dict[str, Any]:
    if session.get("telegram_message_id"):
        return {"ok": True, "message_id": int(session["telegram_message_id"]), "error_message": ""}

    chat_id = telegram_admin_chat_id()
    if not chat_id:
        return {"ok": False, "message_id": None, "error_message": "Telegram 관리자 Chat ID가 설정되어 있지 않습니다."}

    session_id = int(session["id"])
    message = "\n".join(
        [
            "관리자 페이지 접속 요청이 있습니다.",
            f"장치 ID: {session['device_id']}",
            f"IP: {session['ip_address']}",
            f"브라우저: {session['user_agent']}",
            "승인하시겠습니까?",
        ]
    )
    payload = {
        "chat_id": chat_id,
        "text": message,
        "reply_markup": {
            "inline_keyboard": [
                [
                    {"text": "승인", "callback_data": build_callback_data(session_id, "approve")},
                    {"text": "거부", "callback_data": build_callback_data(session_id, "reject")},
                ]
            ]
        },
    }
    result = telegram_api("sendMessage", payload)
    if not result.get("ok"):
        return {"ok": False, "message_id": None, "error_message": result.get("description") or "Telegram 승인 메시지 전송에 실패했습니다."}
    message_id = result.get("result", {}).get("message_id")
    if message_id:
        execute_one(
            """
            UPDATE admin.admin_login_session
            SET telegram_message_id = %s, updated_at = CURRENT_TIMESTAMP
            WHERE id = %s
            RETURNING id
            """,
            (message_id, session_id),
        )
    return {"ok": bool(message_id), "message_id": message_id, "error_message": "" if message_id else "Telegram 메시지 ID를 확인할 수 없습니다."}


def apply_telegram_auth_callback(callback_query: dict[str, Any]) -> dict[str, Any]:
    data = str(callback_query.get("data") or "")
    parsed = parse_callback_data(data)
    if not parsed:
        return {"ok": False, "status": None, "message": "처리할 수 없는 승인 요청입니다."}

    action, session_id, signature = parsed
    expected = callback_signature(session_id, action)
    if not expected or not hmac.compare_digest(expected, signature):
        return {"ok": False, "status": None, "message": "승인 요청 검증에 실패했습니다."}

    owner_id = telegram_owner_user_id()
    from_user_id = str((callback_query.get("from") or {}).get("id") or "")
    if owner_id and from_user_id != owner_id:
        return {"ok": False, "status": None, "message": "허가되지 않은 Telegram 사용자입니다."}

    status = APPROVED if action == "approve" else REJECTED
    time_column = "approved_at" if status == APPROVED else "rejected_at"
    row = execute_one(
        f"""
        UPDATE admin.admin_login_session
        SET status = %s,
            {time_column} = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = %s AND status = 'PENDING'
        RETURNING id, status
        """,
        (status, session_id),
    )
    return {
        "ok": True,
        "status": row.get("status", status),
        "message": "승인되었습니다." if status == APPROVED else "거부되었습니다.",
    }


def start_telegram_update_poller() -> None:
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
    chat_id = telegram_admin_chat_id()
    if not token or not chat_id:
        print("[telegram] TELEGRAM_BOT_TOKEN 또는 TELEGRAM_OWNER_CHAT_ID/TELEGRAM_CHAT_ID가 없어 승인 폴링을 건너뜁니다.", flush=True)
        return

    def poll() -> None:
        offset = 0
        telegram_api("deleteWebhook", {"drop_pending_updates": False})
        print("[telegram] 관리자 승인 버튼 폴링을 시작합니다.", flush=True)
        while True:
            result = telegram_api("getUpdates", {"offset": offset, "timeout": 25, "allowed_updates": ["callback_query"]})
            if not result.get("ok"):
                time.sleep(5)
                continue
            for update in result.get("result", []):
                offset = max(offset, int(update.get("update_id", 0)) + 1)
                callback_query = update.get("callback_query")
                if not callback_query:
                    continue
                callback_result = apply_telegram_auth_callback(callback_query)
                callback_id = callback_query.get("id")
                if callback_id:
                    telegram_api(
                        "answerCallbackQuery",
                        {"callback_query_id": callback_id, "text": callback_result.get("message") or "처리되었습니다."},
                    )

    thread = threading.Thread(target=poll, name="telegram-admin-auth-poller", daemon=True)
    thread.start()


def find_approved_session(device_id: str, ip_address: str, user_agent: str) -> dict[str, Any]:
    return fetch_one(
        """
        UPDATE admin.admin_login_session
        SET last_seen_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
        WHERE id = (
            SELECT id
            FROM admin.admin_login_session
            WHERE device_id = %s AND ip_address = %s AND user_agent = %s AND status = 'APPROVED'
            ORDER BY approved_at DESC NULLS LAST, id DESC
            LIMIT 1
        )
        RETURNING id, device_id, ip_address, user_agent, status, telegram_message_id,
                  requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
        """,
        (device_id, ip_address, user_agent),
    )


def find_or_create_pending_session(device_id: str, ip_address: str, user_agent: str) -> dict[str, Any]:
    execute_one(
        """
        UPDATE admin.admin_login_session
        SET status = 'LOGGED_OUT',
            logged_out_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE device_id = %s
          AND ip_address = %s
          AND user_agent = %s
          AND status = 'PENDING'
          AND requested_at < CURRENT_TIMESTAMP - (%s || ' minutes')::interval
        RETURNING id
        """,
        (device_id, ip_address, user_agent, PENDING_TIMEOUT_MINUTES),
    )
    pending = fetch_one(
        """
        SELECT id, device_id, ip_address, user_agent, status, telegram_message_id,
               requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
        FROM admin.admin_login_session
        WHERE device_id = %s AND ip_address = %s AND user_agent = %s AND status = 'PENDING'
        ORDER BY requested_at DESC, id DESC
        LIMIT 1
        """,
        (device_id, ip_address, user_agent),
    )
    if pending:
        return pending
    return execute_one(
        """
        INSERT INTO admin.admin_login_session(device_id, ip_address, user_agent, status, requested_at, last_seen_at)
        VALUES (%s, %s, %s, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        RETURNING id, device_id, ip_address, user_agent, status, telegram_message_id,
                  requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
        """,
        (device_id, ip_address, user_agent),
    )


def invalidate_login_sessions(device_id: str, ip_address: str, user_agent: str) -> None:
    execute_one(
        """
        UPDATE admin.admin_login_session
        SET status = 'LOGGED_OUT',
            logged_out_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE device_id = %s
          AND ip_address = %s
          AND user_agent = %s
          AND status IN ('APPROVED', 'PENDING')
        RETURNING id
        """,
        (device_id, ip_address, user_agent),
    )


def session_status(session_id: int) -> dict[str, Any]:
    execute_one(
        """
        UPDATE admin.admin_login_session
        SET status = 'LOGGED_OUT',
            logged_out_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = %s
          AND status = 'PENDING'
          AND requested_at < CURRENT_TIMESTAMP - (%s || ' minutes')::interval
        RETURNING id
        """,
        (session_id, PENDING_TIMEOUT_MINUTES),
    )
    return fetch_one(
        """
        SELECT id, device_id, ip_address, user_agent, status,
               requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
        FROM admin.admin_login_session
        WHERE id = %s
        """,
        (session_id,),
    )


def module_rows() -> list[dict[str, Any]]:
    return fetch_all(
        """
        SELECT module_key, module_group, module_name, description, is_enabled, is_required, run_order
        FROM admin.module_config
        ORDER BY run_order, module_key
        """
    )


def dashboard_summary() -> dict[str, Any]:
    candidate_counts = fetch_one(
        """
        SELECT
            COUNT(*)::int AS candidate_count,
            COUNT(*) FILTER (WHERE status IN ('PUBLISHED', 'DRY_RUN_PUBLISHED', 'NOTIFIED', 'DRY_RUN_NOTIFIED'))::int AS published_count,
            COUNT(*) FILTER (WHERE status = 'DUPLICATE')::int AS duplicate_count,
            COUNT(*) FILTER (WHERE status = 'FAILED')::int AS failed_count
        FROM social_news.candidate
        """
    )
    module_counts = fetch_one(
        """
        SELECT
            COUNT(*)::int AS module_count,
            COUNT(*) FILTER (WHERE is_enabled)::int AS enabled_module_count,
            COUNT(*) FILTER (WHERE NOT is_enabled)::int AS disabled_module_count
        FROM admin.module_config
        """
    )
    latest_cycle = fetch_one(
        """
        SELECT status, dry_run, started_at, ended_at
        FROM social_news.pipeline_cycle
        ORDER BY started_at DESC
        LIMIT 1
        """
    )
    return {
        **candidate_counts,
        **module_counts,
        "latest_cycle": latest_cycle or None,
        "api_connected": True,
        "database": "foreign_worker_job_info",
    }


def candidate_rows() -> list[dict[str, Any]]:
    return fetch_all(
        """
        SELECT id, category, 'KR' AS region, title, source_name, source_type, evaluation_score,
               duplicate_risk_score, status, short_summary, selection_reason, skip_reason, collected_at
        FROM social_news.candidate
        ORDER BY collected_at DESC, id DESC
        LIMIT 100
        """
    )


def log_rows() -> list[dict[str, Any]]:
    return fetch_all(
        """
        SELECT id::text AS id, 'Pipeline' AS bot, severity AS level, error_message AS message,
               occurred_at AS time, '-' AS latency
        FROM social_news.pipeline_error_log
        ORDER BY occurred_at DESC
        LIMIT 50
        """
    )


class AdminRequestHandler(BaseHTTPRequestHandler):
    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self._send_common_headers()
        self.end_headers()

    def do_GET(self) -> None:
        try:
            path = urlparse(self.path).path
            if not self._is_public_get(path) and not self._has_approved_cookie():
                self._send_json({"error": "unauthorized", "message": "관리자 승인이 필요합니다."}, status=401)
                return

            if path == "/api/health":
                self._send_json({"ok": True, "database": "foreign_worker_job_info"})
            elif path.startswith("/api/admin/auth/status/"):
                self._handle_auth_status(path)
            elif path == "/api/admin/modules":
                self._send_json({"items": module_rows()})
            elif path == "/api/dashboard/summary":
                self._send_json(dashboard_summary())
            elif path == "/api/social/news/candidates":
                self._send_json({"items": candidate_rows()})
            elif path == "/api/logs/recent":
                self._send_json({"items": log_rows()})
            else:
                self._send_json({"error": "not_found", "message": "요청한 API를 찾을 수 없습니다."}, status=404)
        except Exception:
            self._send_json({"error": "server_error", "message": "서버 처리 중 오류가 발생했습니다."}, status=500)

    def do_POST(self) -> None:
        parsed_url = urlparse(self.path)
        path = parsed_url.path
        try:
            if path not in PUBLIC_POST_PATHS and not self._has_approved_cookie():
                self._send_json({"error": "unauthorized", "message": "관리자 승인이 필요합니다."}, status=401)
                return

            if path == "/api/admin/auth/check":
                self._handle_auth_check()
            elif path == "/api/admin/auth/logout":
                self._handle_logout()
            elif path == "/api/admin/telegram/callback":
                self._handle_telegram_callback(parsed_url)
            else:
                self._send_json({"error": "not_found", "message": "요청한 API를 찾을 수 없습니다."}, status=404)
        except Exception:
            self._send_json({"error": "server_error", "message": "서버 처리 중 오류가 발생했습니다."}, status=500)

    def _is_public_get(self, path: str) -> bool:
        return path in PUBLIC_GET_PATHS or any(path.startswith(prefix) for prefix in PUBLIC_GET_PREFIXES)

    def _read_json(self) -> dict[str, Any]:
        length = int(self.headers.get("Content-Length", "0") or "0")
        if length <= 0:
            return {}
        raw = self.rfile.read(length).decode("utf-8", errors="replace")
        return json.loads(raw) if raw else {}

    def _cookie_session_id(self) -> int | None:
        raw_cookie = self.headers.get("Cookie", "")
        jar = cookies.SimpleCookie()
        jar.load(raw_cookie)
        morsel = jar.get(SESSION_COOKIE)
        if not morsel:
            return None
        try:
            return int(morsel.value)
        except ValueError:
            return None

    def _has_approved_cookie(self) -> bool:
        session_id = self._cookie_session_id()
        device_id = self.headers.get("X-Device-Id", "").strip()
        user_agent = self.headers.get("User-Agent", "").strip()
        if not device_id or not user_agent:
            return False
        ip_address = client_ip(self)
        if session_id:
            row = fetch_one(
                """
                UPDATE admin.admin_login_session
                SET last_seen_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
                WHERE id = %s
                  AND device_id = %s
                  AND ip_address = %s
                  AND user_agent = %s
                  AND status = 'APPROVED'
                RETURNING id
                """,
                (session_id, device_id, ip_address, user_agent),
            )
            if row:
                return True
        return bool(find_approved_session(device_id, ip_address, user_agent))

    def _handle_auth_check(self) -> None:
        payload = self._read_json()
        device_id = str(payload.get("deviceId") or "").strip()
        user_agent = str(payload.get("userAgent") or self.headers.get("User-Agent") or "").strip()
        force_approval_request = bool(payload.get("forceApprovalRequest"))
        if not device_id or not user_agent:
            self._send_json({"error": "bad_request", "message": "장치 식별값을 확인할 수 없습니다."}, status=400)
            return

        ip_address = client_ip(self)
        if force_approval_request:
            invalidate_login_sessions(device_id, ip_address, user_agent)
        else:
            approved = find_approved_session(device_id, ip_address, user_agent)
            if approved:
                self._send_auth_response(approved)
                return

        pending = find_or_create_pending_session(device_id, ip_address, user_agent)
        send_result = send_approval_request(pending)
        if not send_result.get("ok"):
            self._send_json(
                {
                    "sessionId": pending.get("id"),
                    "status": "ERROR",
                    "approved": False,
                    "message": f"Telegram 승인 메시지 전송에 실패했습니다. {send_result.get('error_message')}",
                },
                status=503,
                set_cookie=pending.get("id"),
            )
            return
        self._send_auth_response(pending)

    def _handle_auth_status(self, path: str) -> None:
        try:
            session_id = int(path.rstrip("/").split("/")[-1])
        except ValueError:
            self._send_json({"error": "bad_request", "message": "세션 정보를 확인할 수 없습니다."}, status=400)
            return
        row = session_status(session_id)
        if not row:
            self._send_json({"error": "not_found", "message": "세션 정보를 찾을 수 없습니다."}, status=404)
            return
        device_id = self.headers.get("X-Device-Id", "").strip()
        user_agent = self.headers.get("User-Agent", "").strip()
        if (
            not device_id
            or not user_agent
            or row.get("device_id") != device_id
            or row.get("ip_address") != client_ip(self)
            or row.get("user_agent") != user_agent
        ):
            self._send_json({"error": "forbidden", "message": "접속 아이디가 허가되지 않습니다."}, status=403)
            return
        if row.get("status") == APPROVED:
            row = execute_one(
                """
                UPDATE admin.admin_login_session
                SET last_seen_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
                WHERE id = %s
                RETURNING id, device_id, ip_address, user_agent, status,
                          requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
                """,
                (session_id,),
            )
        self._send_auth_response(row)

    def _handle_logout(self) -> None:
        session_id = self._cookie_session_id()
        payload = self._read_json()
        device_id = str(payload.get("deviceId") or self.headers.get("X-Device-Id") or "").strip()
        user_agent = str(payload.get("userAgent") or self.headers.get("User-Agent") or "").strip()
        if session_id:
            execute_one(
                """
                UPDATE admin.admin_login_session
                SET status = 'LOGGED_OUT',
                    logged_out_at = CURRENT_TIMESTAMP,
                    updated_at = CURRENT_TIMESTAMP
                WHERE id = %s AND status IN ('APPROVED', 'PENDING')
                RETURNING id
                """,
                (session_id,),
            )
        if device_id and user_agent:
            execute_one(
                """
                UPDATE admin.admin_login_session
                SET status = 'LOGGED_OUT',
                    logged_out_at = CURRENT_TIMESTAMP,
                    updated_at = CURRENT_TIMESTAMP
                WHERE device_id = %s
                  AND ip_address = %s
                  AND user_agent = %s
                  AND status IN ('APPROVED', 'PENDING')
                RETURNING id
                """,
                (device_id, client_ip(self), user_agent),
            )
        self._send_json({"status": LOGGED_OUT, "message": "로그아웃되었습니다."}, clear_cookie=True)

    def _handle_telegram_callback(self, parsed_url) -> None:
        if not verify_callback_secret(self, parsed_url):
            self._send_json({"ok": False, "message": "Callback 검증에 실패했습니다."}, status=403)
            return
        payload = self._read_json()
        callback_query = payload.get("callback_query") or payload
        result = apply_telegram_auth_callback(callback_query)
        callback_id = callback_query.get("id")
        if callback_id:
            telegram_api(
                "answerCallbackQuery",
                {"callback_query_id": callback_id, "text": result.get("message") or "처리되었습니다."},
            )
        self._send_json(result, status=200 if result.get("ok") else 403)

    def _send_auth_response(self, session: dict[str, Any], message: str | None = None) -> None:
        status = session.get("status")
        response_message = message or {
            PENDING: "Telegram에서 접속 승인을 완료해주세요.",
            APPROVED: "접속이 승인되었습니다.",
            REJECTED: "접속이 거부되었습니다.",
            LOGGED_OUT: "승인 요청 시간이 만료되었습니다. 다시 승인 요청을 눌러주세요.",
        }.get(status, "관리자 접속 확인 중입니다.")
        self._send_json(
            {
                "sessionId": session.get("id"),
                "status": status,
                "approved": status == APPROVED,
                "message": response_message,
            },
            set_cookie=session.get("id"),
        )

    def _send_common_headers(self) -> None:
        origin = self.headers.get("Origin", "").strip().rstrip("/")
        if not origin:
            referer = self.headers.get("Referer", "").strip()
            parsed_referer = urlparse(referer)
            if parsed_referer.scheme and parsed_referer.netloc:
                origin = f"{parsed_referer.scheme}://{parsed_referer.netloc}".rstrip("/")
        if origin not in ALLOWED_ADMIN_ORIGINS and origin.startswith("http://localhost:5173"):
            origin = "http://localhost:5173"
        if origin not in ALLOWED_ADMIN_ORIGINS and origin.startswith("http://127.0.0.1:5173"):
            origin = "http://127.0.0.1:5173"
        self.send_header("Access-Control-Allow-Origin", origin if origin in ALLOWED_ADMIN_ORIGINS else "http://127.0.0.1:5173")
        self.send_header("Vary", "Origin")
        self.send_header("Access-Control-Allow-Credentials", "true")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header(
            "Access-Control-Allow-Headers",
            "Content-Type, X-Device-Id, X-Admin-Telegram-Secret, X-Telegram-Bot-Api-Secret-Token",
        )

    def _send_json(
        self,
        payload: dict[str, Any],
        status: int = 200,
        set_cookie: Any = None,
        clear_cookie: bool = False,
    ) -> None:
        body = json.dumps(json_ready(payload), ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self._send_common_headers()
        if clear_cookie:
            self.send_header("Set-Cookie", f"{SESSION_COOKIE}=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax")
        elif set_cookie:
            self.send_header("Set-Cookie", f"{SESSION_COOKIE}={set_cookie}; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax")
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format: str, *args: Any) -> None:
        return


def main(argv: list[str] | None = None) -> int:
    load_env_file()
    parser = argparse.ArgumentParser(description="Run the WorkConnect admin API server.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    args = parser.parse_args(argv)

    ensure_auth_schema()
    start_telegram_update_poller()
    server = ThreadingHTTPServer((args.host, args.port), AdminRequestHandler)
    print(f"Admin API listening on http://{args.host}:{args.port}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
