"""Admin API for the Vue dashboard with Telegram approval auth."""

from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import json
import os
import subprocess
import threading
import time
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from http import cookies
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any
from urllib.parse import parse_qs, urlparse
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from ..jobs.employment_collector import EmploymentJobCollector
from ..jobs.repository import JobCollectorRepository
from ..occupation.collectors import JobInfoCollector, OccupationInfoCollector
from ..occupation.repository import OccupationRepository
from ..social.news.collector.article_text_extractor import fetch_article_metadata
from ..social.news.collector.google_news_url_resolver import is_acceptable_source_url, resolve_google_news_url
from ..social.news.evaluator.candidate_evaluator import CandidateEvaluator
from ..social.news.pipeline import NewsPipeline, today_cycle_id
from ..social.news.publisher.facebook_publisher import FacebookPublisher, facebook_runtime_config_summary
from ..social.news.repository.news_repository import NewsRepository, safe_url
from ..storage.db.postgres import connect, load_env_file, safe_connection_summary


SESSION_COOKIE = "workconnect_admin_session"
APPROVED = "APPROVED"
PENDING = "PENDING"
REJECTED = "REJECTED"
LOGGED_OUT = "LOGGED_OUT"
PENDING_TIMEOUT_MINUTES = 3
BOT_KEY = "social_news_bot"
BOT_STATUS_LABELS = {
    "RUNNING": "실행 중",
    "STOPPED": "중지됨",
    "ERROR": "장애",
    "STARTING": "시작 중",
    "STOPPING": "종료 중",
}
BOT_STOP_EVENT = threading.Event()
BOT_THREAD: threading.Thread | None = None
JOB_COLLECTOR_STATUS = {
    "status": "STOPPED",
    "lastErrorMessage": None,
    "schedulerEnabled": False,
    "nextRunAt": None,
}
JOB_COLLECTOR_LOCK = threading.Lock()
JOB_COLLECTOR_THREAD: threading.Thread | None = None
JOB_COLLECTOR_SCHEDULER_THREAD: threading.Thread | None = None
JOB_COLLECTOR_SCHEDULER_STOP = threading.Event()
LLAMA_STATE = {
    "enabled": False,
    "connected": False,
    "endpoint": "http://localhost:11434",
    "model": "llama3.1",
    "status": "DISABLED",
    "message": "로컬 LLaMA 비활성",
}
LLAMA_PROCESS: subprocess.Popen | None = None
PUBLIC_POST_PATHS = {"/api/admin/auth/check", "/api/admin/auth/logout", "/api/admin/telegram/callback"}
PUBLIC_GET_PREFIXES = ("/api/admin/auth/status/",)
PUBLIC_GET_PATHS = {"/api/health"}
ALLOWED_ADMIN_ORIGINS = {
    "http://127.0.0.1:5173",
    "http://localhost:5173",
}


def ensure_auth_schema() -> None:
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                CREATE SCHEMA IF NOT EXISTS admin;

                CREATE TABLE IF NOT EXISTS admin.module_config (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    module_key VARCHAR(120) NOT NULL UNIQUE,
                    module_group VARCHAR(60) NOT NULL,
                    module_name VARCHAR(120) NOT NULL,
                    description TEXT,
                    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
                    is_required BOOLEAN NOT NULL DEFAULT FALSE,
                    run_order INTEGER NOT NULL DEFAULT 100,
                    config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                );

                INSERT INTO admin.module_config(module_key, module_group, module_name, description, is_enabled, run_order)
                VALUES
                    ('social_news_bot', 'bot', '소셜 뉴스 봇', '뉴스 수집, 요약, 평가, 게시 자동화 런타임', TRUE, 10),
                    ('job_collector_bot', 'bot', '채용정보 수집 봇', '고용24/워크넷 채용정보 수집 런타임', FALSE, 20)
                ON CONFLICT (module_key) DO NOTHING;

                CREATE TABLE IF NOT EXISTS admin.admin_login_session (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    device_id VARCHAR(120) NOT NULL,
                    ip_address VARCHAR(80) NOT NULL,
                    user_agent TEXT NOT NULL,
                    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
                    telegram_message_id BIGINT,
                    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    approved_at TIMESTAMPTZ,
                    rejected_at TIMESTAMPTZ,
                    logged_out_at TIMESTAMPTZ,
                    last_seen_at TIMESTAMPTZ,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ck_admin_login_session_status
                        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'LOGGED_OUT'))
                );

                CREATE INDEX IF NOT EXISTS idx_admin_login_session_lookup
                ON admin.admin_login_session(device_id, ip_address, left(user_agent, 180), status);

                CREATE UNIQUE INDEX IF NOT EXISTS ux_admin_login_session_approved_active
                ON admin.admin_login_session(device_id, ip_address, user_agent)
                WHERE status = 'APPROVED';

                CREATE UNIQUE INDEX IF NOT EXISTS ux_admin_login_session_pending_active
                ON admin.admin_login_session(device_id, ip_address, user_agent)
                WHERE status = 'PENDING';

                CREATE TABLE IF NOT EXISTS admin.admin_bot_runtime (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    bot_key VARCHAR(120) NOT NULL UNIQUE,
                    status VARCHAR(30) NOT NULL DEFAULT 'STOPPED',
                    last_started_at TIMESTAMPTZ,
                    last_stopped_at TIMESTAMPTZ,
                    last_error_at TIMESTAMPTZ,
                    last_error_message TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ck_admin_bot_runtime_status
                        CHECK (status IN ('RUNNING', 'STOPPED', 'ERROR', 'STARTING', 'STOPPING'))
                );

                INSERT INTO admin.admin_bot_runtime(bot_key, status)
                VALUES ('social_news_bot', 'STOPPED')
                ON CONFLICT (bot_key) DO NOTHING;

                UPDATE admin.module_config
                SET is_enabled = TRUE, updated_at = CURRENT_TIMESTAMP
                WHERE module_key IN ('collector.naver', 'collector.google', 'publish.facebook', 'notify.telegram');

                UPDATE admin.module_config
                SET is_enabled = FALSE, updated_at = CURRENT_TIMESTAMP
                WHERE module_key = 'collector.rss';
                """
            )
        conn.commit()


def fetch_all(sql: str, params: tuple[Any, ...] = ()) -> list[dict[str, Any]]:
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            columns = [column.name for column in cur.description]
            return [dict(zip(columns, row)) for row in cur.fetchall()]


def fetch_one(sql: str, params: tuple[Any, ...] = ()) -> dict[str, Any]:
    rows = fetch_all(sql, params)
    return rows[0] if rows else {}


def execute_one(sql: str, params: tuple[Any, ...] = ()) -> dict[str, Any]:
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            row = cur.fetchone()
            columns = [column.name for column in cur.description] if cur.description else []
        conn.commit()
    return dict(zip(columns, row)) if row else {}


def bot_runtime_row() -> dict[str, Any]:
    return fetch_one(
        """
        SELECT bot_key, status, last_started_at, last_stopped_at, last_error_at, last_error_message
        FROM admin.admin_bot_runtime
        WHERE bot_key = %s
        """,
        (BOT_KEY,),
    )


def format_bot_status(row: dict[str, Any]) -> dict[str, Any]:
    status = row.get("status") or "STOPPED"
    return {
        "status": status,
        "label": BOT_STATUS_LABELS.get(status, status),
        "lastStartedAt": row.get("last_started_at"),
        "lastStoppedAt": row.get("last_stopped_at"),
        "lastErrorAt": row.get("last_error_at"),
        "lastErrorMessage": row.get("last_error_message"),
    }


def news_repository() -> NewsRepository:
    return NewsRepository()


def job_repository() -> JobCollectorRepository:
    return JobCollectorRepository()


def job_collector() -> EmploymentJobCollector:
    return EmploymentJobCollector(job_repository())


def occupation_repository() -> OccupationRepository:
    return OccupationRepository()


def job_info_collector() -> JobInfoCollector:
    return JobInfoCollector(occupation_repository())


def occupation_info_collector() -> OccupationInfoCollector:
    return OccupationInfoCollector(occupation_repository())


def write_bot_log(step: str, status: str, message: str) -> None:
    try:
        news_repository().insert_pipeline_log(step=step, status=status, message=message)
    except Exception:
        pass


def set_bot_status(status: str, error_message: str | None = None) -> dict[str, Any]:
    assignments = ["status = %s", "updated_at = CURRENT_TIMESTAMP"]
    params: list[Any] = [status]
    if status == "RUNNING":
        assignments.append("last_started_at = CURRENT_TIMESTAMP")
        assignments.append("last_error_message = NULL")
    elif status == "STOPPED":
        assignments.append("last_stopped_at = CURRENT_TIMESTAMP")
    elif status == "ERROR":
        assignments.append("last_error_at = CURRENT_TIMESTAMP")
        assignments.append("last_error_message = %s")
        params.append((error_message or "알 수 없는 오류")[:500])
    params.append(BOT_KEY)
    row = execute_one(
        f"""
        UPDATE admin.admin_bot_runtime
        SET {", ".join(assignments)}
        WHERE bot_key = %s
        RETURNING bot_key, status, last_started_at, last_stopped_at, last_error_at, last_error_message
        """,
        tuple(params),
    )
    return format_bot_status(row)


def run_bot_loop() -> None:
    try:
        from ..crew_team.social.news_bot import NewsBot

        keyword = os.environ.get("NEWS_COLLECTOR_KEYWORD", "foreign worker visa Korea")
        interval = int(os.environ.get("NEWS_COLLECTOR_CYCLE_INTERVAL_MINUTES", "30")) * 60
        failure_limit = int(os.environ.get("NEWS_BOT_CONSECUTIVE_FAILURE_LIMIT", "3"))
        consecutive_failures = 0
        write_bot_log("bot", "STARTED", f"소셜 뉴스 봇 시작: 검색어 '{keyword}'")
        while not BOT_STOP_EVENT.is_set():
            llama = ensure_llama(start_command=True)
            write_bot_log("llama", "COMPLETED" if llama.get("connected") else "FAILED", f"LLaMA 상태 확인: {llama.get('message')} / 모델 {llama.get('model')}")
            if not llama.get("connected"):
                write_bot_log("cycle", "FAILED", "Local LLaMA 연결 실패로 이번 수집 사이클을 건너뜁니다.")
                if BOT_STOP_EVENT.wait(60):
                    break
                continue
            write_bot_log("cycle", "STARTED", "뉴스 자동 게시 사이클 시작")
            result = NewsBot().run(keyword=keyword, dry_run=False, limit=1)
            publish_results = result.get("publish_results") or []
            selection_log = result.get("selection_log") or {}
            no_publish_code = selection_log.get("no_publish_code") or ""
            write_bot_log(
                "cycle",
                "COMPLETED",
                f"사이클 완료: 수집 {result.get('collected_count', 0)}건, 저장 {result.get('saved_count', 0)}건, 게시 후보 {result.get('selected_count', 0)}건",
            )
            if result.get("selected_count", 0) == 0 and no_publish_code == "WAITING_COOLDOWN":
                write_bot_log(
                    "facebook_publish",
                    "WAITING",
                    (
                        f"Facebook 게시 대기: 쿨다운 적용 중, READY {selection_log.get('ready_count', 0)}건, "
                        f"후보풀 {selection_log.get('candidate_pool_count', 0)}건, "
                        f"남은 {int((int(selection_log.get('cooldown_remaining') or 0) + 59) // 60)}분"
                    ),
                )
            if result.get("selected_count", 0) == 0 and no_publish_code != "WAITING_COOLDOWN":
                write_bot_log(
                    "facebook_publish",
                    "SKIPPED",
                    f"Facebook 게시 안 함: 게시 후보 0건, threshold {float(result.get('threshold') or 0):.0f}점 미달 또는 중복 제외",
                )
            if publish_results and all(item.get("status") == "FAILED" for item in publish_results):
                consecutive_failures += 1
                write_bot_log("cycle", "FAILED", f"게시 실패 누적: {consecutive_failures}/{failure_limit}")
            else:
                consecutive_failures = 0
            if consecutive_failures >= failure_limit:
                raise RuntimeError("뉴스 자동 게시 연속 실패로 봇을 장애 상태로 전환합니다.")
            write_bot_log("cooldown", "WAITING", f"다음 수집까지 {max(interval, 30) // 60}분 대기")
            if BOT_STOP_EVENT.wait(max(interval, 30)):
                break
        write_bot_log("bot", "STOPPED", "소셜 뉴스 봇 종료")
        set_bot_status("STOPPED")
    except Exception as exc:
        BOT_STOP_EVENT.set()
        write_bot_log("bot", "FAILED", f"봇 장애 발생: {str(exc)[:180]}")
        set_bot_status("ERROR", str(exc))

def start_bot() -> dict[str, Any]:
    global BOT_THREAD
    row = bot_runtime_row()
    if row.get("status") == "ERROR":
        return format_bot_status(row)
    if BOT_THREAD and BOT_THREAD.is_alive():
        return set_bot_status("RUNNING")
    BOT_STOP_EVENT.clear()
    set_bot_status("STARTING")
    write_bot_log("bot", "STARTING", "소셜 뉴스 봇 시작 요청")
    BOT_THREAD = threading.Thread(target=run_bot_loop, name="workconnect-social-news-bot", daemon=True)
    BOT_THREAD.start()
    return set_bot_status("RUNNING")


def stop_bot() -> dict[str, Any]:
    if BOT_THREAD and BOT_THREAD.is_alive():
        set_bot_status("STOPPING")
        BOT_STOP_EVENT.set()
        write_bot_log("bot", "STOPPING", "소셜 뉴스 봇 종료 요청")
        return set_bot_status("STOPPED")
    BOT_STOP_EVENT.set()
    write_bot_log("bot", "STOPPED", "소셜 뉴스 봇이 이미 중지 상태입니다.")
    return set_bot_status("STOPPED")


def reset_bot_error() -> dict[str, Any]:
    BOT_STOP_EVENT.set()
    return set_bot_status("STOPPED")


def job_collector_settings() -> dict[str, Any]:
    return job_repository().settings()


def update_job_collector_settings(payload: dict[str, Any]) -> dict[str, Any]:
    return job_repository().update_settings(payload)


def format_job_log(log: dict[str, Any] | None) -> dict[str, Any] | None:
    if not log:
        return None
    return {
        "id": log.get("id"),
        "startedAt": log.get("started_at"),
        "endedAt": log.get("ended_at"),
        "pageFrom": log.get("page_from"),
        "pageTo": log.get("page_to"),
        "display": log.get("display"),
        "sortOrderBy": log.get("sort_order_by"),
        "totalReceived": log.get("total_received"),
        "insertedCount": log.get("inserted_count"),
        "updatedCount": log.get("updated_count"),
        "skippedCount": log.get("skipped_count"),
        "failedCount": log.get("failed_count"),
        "failedPages": log.get("failedPages", []),
        "status": log.get("status"),
        "errorMessage": log.get("error_message"),
    }


def clamp_query_int(query: dict[str, list[str]], key: str, default: int, minimum: int = 0, maximum: int = 100) -> int:
    try:
        value = int(query.get(key, [default])[0])
    except (TypeError, ValueError):
        value = default
    return max(minimum, min(maximum, value))


def job_collector_logs(limit: int = 50, offset: int = 0) -> list[dict[str, Any]]:
    return [format_job_log(log) for log in job_repository().recent_logs(limit=limit, offset=offset)]


def job_posting_rows() -> list[dict[str, Any]]:
    return job_repository().list_postings(limit=200)


def occupation_dashboard() -> dict[str, Any]:
    return occupation_repository().dashboard()


def occupation_job_rows(query: dict[str, list[str]]) -> dict[str, Any]:
    return occupation_repository().list_jobs(
        page=clamp_query_int(query, "page", 1, minimum=1, maximum=100000),
        size=clamp_query_int(query, "size", 20, minimum=1, maximum=100),
        keyword=str(query.get("keyword", [""])[0]).strip(),
        job_code=str(query.get("job_code", [""])[0]).strip(),
        active_yn=str(query.get("active_yn", [""])[0]).strip().upper(),
    )


def occupation_job_detail(item_id: int) -> dict[str, Any]:
    return occupation_repository().get_job(item_id)


def occupation_rows(query: dict[str, list[str]]) -> dict[str, Any]:
    return occupation_repository().list_occupations(
        page=clamp_query_int(query, "page", 1, minimum=1, maximum=100000),
        size=clamp_query_int(query, "size", 20, minimum=1, maximum=100),
        keyword=str(query.get("keyword", [""])[0]).strip(),
        occupation_code=str(query.get("occupation_code", [""])[0]).strip(),
        active_yn=str(query.get("active_yn", [""])[0]).strip().upper(),
    )


def occupation_detail(item_id: int) -> dict[str, Any]:
    return occupation_repository().get_occupation(item_id)


def occupation_keyword_rows(query: dict[str, list[str]]) -> dict[str, Any]:
    return occupation_repository().list_keyword_mappings(
        page=clamp_query_int(query, "page", 1, minimum=1, maximum=100000),
        size=clamp_query_int(query, "size", 50, minimum=1, maximum=100),
        keyword=str(query.get("keyword", [""])[0]).strip(),
        language_code=str(query.get("language_code", [""])[0]).strip(),
    )


def occupation_collect_logs(query: dict[str, list[str]]) -> list[dict[str, Any]]:
    return occupation_repository().collect_logs(
        limit=clamp_query_int(query, "limit", 50, minimum=1, maximum=100),
        offset=clamp_query_int(query, "offset", 0, minimum=0, maximum=10000),
    )


def run_occupation_job_collection(payload: dict[str, Any]) -> dict[str, Any]:
    return job_info_collector().run(
        page_from=int(payload.get("pageFrom") or 1),
        page_to=int(payload.get("pageTo") or payload.get("pageFrom") or 1),
        size=int(payload.get("size") or 100),
    )


def run_occupation_info_collection(payload: dict[str, Any]) -> dict[str, Any]:
    return occupation_info_collector().run(
        page_from=int(payload.get("pageFrom") or 1),
        page_to=int(payload.get("pageTo") or payload.get("pageFrom") or 1),
        size=int(payload.get("size") or 100),
    )


def job_collector_status() -> dict[str, Any]:
    settings = job_collector_settings()
    latest = format_job_log(job_repository().latest_log())
    status = JOB_COLLECTOR_STATUS["status"]
    scheduler_enabled = bool(settings.get("schedulerEnabled"))
    if JOB_COLLECTOR_THREAD and JOB_COLLECTOR_THREAD.is_alive():
        status = "RUNNING"
    elif status == "RUNNING":
        status = "STOPPED"
        JOB_COLLECTOR_STATUS["status"] = "STOPPED"
    if JOB_COLLECTOR_SCHEDULER_THREAD and JOB_COLLECTOR_SCHEDULER_THREAD.is_alive():
        scheduler_enabled = True
    return {
        "status": status,
        "lastRunAt": latest.get("startedAt") if latest else None,
        "nextRunAt": JOB_COLLECTOR_STATUS.get("nextRunAt"),
        "schedulerEnabled": scheduler_enabled,
        "authKeyConfigured": bool(os.environ.get("EMPLOYEE_24_OPEN_API_EMPLOYMENT_KEY", "").strip()),
        "settings": settings,
        "latest": latest,
        "lastErrorMessage": JOB_COLLECTOR_STATUS.get("lastErrorMessage") or (latest or {}).get("errorMessage"),
    }


def run_job_collection_now(smoke: bool = False) -> dict[str, Any]:
    with JOB_COLLECTOR_LOCK:
        JOB_COLLECTOR_STATUS.update({"status": "RUNNING", "lastErrorMessage": None})
        settings = job_collector_settings()
        try:
            if smoke:
                result = job_collector().run(display=10, start_page_from=1, start_page_to=1, sort_order_by="DESC", delay_seconds=0.5)
            else:
                result = job_collector().run(
                    display=int(settings["display"]),
                    start_page_from=int(settings["startPageFrom"]),
                    start_page_to=int(settings["startPageTo"]),
                    sort_order_by=str(settings["sortOrderBy"]),
                    delay_seconds=0.7,
                )
            JOB_COLLECTOR_STATUS["status"] = "ERROR" if result["status"] == "FAILED" else "STOPPED"
            JOB_COLLECTOR_STATUS["lastErrorMessage"] = result.get("errorMessage")
            return result
        except Exception as exc:
            JOB_COLLECTOR_STATUS.update({"status": "ERROR", "lastErrorMessage": str(exc)[:300]})
            raise


def start_job_collection(smoke: bool = False) -> dict[str, Any]:
    global JOB_COLLECTOR_THREAD
    if JOB_COLLECTOR_THREAD and JOB_COLLECTOR_THREAD.is_alive():
        return {"accepted": False, "message": "채용정보 수집이 이미 실행 중입니다.", "status": job_collector_status()}

    def runner() -> None:
        try:
            run_job_collection_now(smoke=smoke)
        except Exception:
            return

    JOB_COLLECTOR_THREAD = threading.Thread(target=runner, name="workconnect-job-collector", daemon=True)
    JOB_COLLECTOR_THREAD.start()
    JOB_COLLECTOR_STATUS.update({"status": "RUNNING", "lastErrorMessage": None})
    return {"accepted": True, "message": "채용정보 수집을 시작했습니다.", "status": job_collector_status()}


def job_scheduler_loop() -> None:
    while not JOB_COLLECTOR_SCHEDULER_STOP.is_set():
        settings = job_collector_settings()
        interval_minutes = int(settings["intervalMinutes"])
        next_run = datetime.now(timezone.utc) + timedelta(minutes=interval_minutes)
        JOB_COLLECTOR_STATUS["nextRunAt"] = next_run.isoformat()
        if JOB_COLLECTOR_SCHEDULER_STOP.wait(max(60, interval_minutes * 60)):
            break
        try:
            run_job_collection_now(smoke=False)
        except Exception:
            pass
    job_repository().set_scheduler_enabled(False)
    JOB_COLLECTOR_STATUS.update({"schedulerEnabled": False, "nextRunAt": None})


def start_job_scheduler() -> dict[str, Any]:
    global JOB_COLLECTOR_SCHEDULER_THREAD
    if JOB_COLLECTOR_SCHEDULER_THREAD and JOB_COLLECTOR_SCHEDULER_THREAD.is_alive():
        return job_collector_status()
    JOB_COLLECTOR_SCHEDULER_STOP.clear()
    job_repository().set_scheduler_enabled(True)
    JOB_COLLECTOR_STATUS["schedulerEnabled"] = True
    JOB_COLLECTOR_SCHEDULER_THREAD = threading.Thread(target=job_scheduler_loop, name="workconnect-job-collector-scheduler", daemon=True)
    JOB_COLLECTOR_SCHEDULER_THREAD.start()
    return job_collector_status()


def stop_job_scheduler() -> dict[str, Any]:
    JOB_COLLECTOR_SCHEDULER_STOP.set()
    job_repository().set_scheduler_enabled(False)
    JOB_COLLECTOR_STATUS.update({"schedulerEnabled": False, "nextRunAt": None})
    return job_collector_status()


def is_llama_connected(endpoint: str) -> bool:
    try:
        with urlopen(f"{endpoint.rstrip('/')}/api/tags", timeout=3) as response:
            return 200 <= response.status < 300
    except Exception:
        return False


def llama_config() -> tuple[bool, str, str]:
    enabled = os.environ.get("LOCAL_LLAMA_ENABLED", "true").lower() in {"1", "true", "yes", "on"}
    endpoint = os.environ.get("LOCAL_LLAMA_ENDPOINT", os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")).rstrip("/")
    model = os.environ.get("LOCAL_LLAMA_MODEL") or os.environ.get("LOCAL_MODEL_GENERAL") or os.environ.get("LOCAL_MODEL_MASTER") or "llama3.1"
    return enabled, endpoint, model


def unload_llama_model(endpoint: str, model: str) -> None:
    if not model:
        return
    payload = json.dumps({"model": model, "prompt": "", "stream": False, "keep_alive": 0}).encode("utf-8")
    request = Request(
        f"{endpoint.rstrip('/')}/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(request, timeout=5):
            return
    except Exception:
        return


def ensure_llama(start_command: bool = True) -> dict[str, Any]:
    global LLAMA_PROCESS
    enabled, endpoint, model = llama_config()
    LLAMA_STATE.update({"enabled": enabled, "endpoint": endpoint, "model": model})
    if not enabled:
        LLAMA_STATE.update({"connected": False, "status": "DISABLED", "message": "로컬 LLaMA 비활성"})
        return LLAMA_STATE
    if is_llama_connected(endpoint):
        LLAMA_STATE.update({"connected": True, "status": "CONNECTED", "message": "로컬 LLaMA 연결됨"})
        return LLAMA_STATE
    if start_command:
        command = os.environ.get("LOCAL_LLAMA_COMMAND", "ollama serve")
        LLAMA_STATE.update({"connected": False, "status": "STARTING", "message": "로컬 LLaMA 시작 중"})
        try:
            if not LLAMA_PROCESS or LLAMA_PROCESS.poll() is not None:
                LLAMA_PROCESS = subprocess.Popen(command, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            for _ in range(10):
                time.sleep(1)
                if is_llama_connected(endpoint):
                    LLAMA_STATE.update({"connected": True, "status": "CONNECTED", "message": "로컬 LLaMA 연결됨"})
                    return LLAMA_STATE
        except Exception as exc:
            LLAMA_STATE.update({"connected": False, "status": "ERROR", "message": f"로컬 LLaMA 실행 실패: {str(exc)[:120]}"})
            return LLAMA_STATE
    LLAMA_STATE.update({"connected": False, "status": "DISCONNECTED", "message": "로컬 LLaMA 연결 실패"})
    return LLAMA_STATE


def stop_llama() -> dict[str, Any]:
    global LLAMA_PROCESS
    enabled, endpoint, model = llama_config()
    LLAMA_STATE.update({"enabled": enabled, "endpoint": endpoint, "model": model, "status": "STOPPING", "message": "로컬 LLaMA 종료 중"})
    unload_llama_model(endpoint, model)
    if LLAMA_PROCESS and LLAMA_PROCESS.poll() is None:
        try:
            LLAMA_PROCESS.terminate()
            LLAMA_PROCESS.wait(timeout=5)
        except Exception:
            try:
                LLAMA_PROCESS.kill()
            except Exception:
                pass
    LLAMA_PROCESS = None
    if is_llama_connected(endpoint):
        LLAMA_STATE.update({"connected": False, "status": "DISCONNECTED", "message": "모델 메모리 해제 요청 완료. 외부 LLaMA 서버는 실행 중입니다."})
    else:
        LLAMA_STATE.update({"connected": False, "status": "DISABLED", "message": "로컬 LLaMA 중지됨"})
    return LLAMA_STATE


def json_ready(value: Any) -> Any:
    if isinstance(value, list):
        return [json_ready(item) for item in value]
    if isinstance(value, dict):
        return {key: json_ready(item) for key, item in value.items()}
    if isinstance(value, Decimal):
        return float(value)
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return value


def sanitize_news_url_fields(row: dict[str, Any]) -> dict[str, Any]:
    row["source_url"] = safe_url(row.get("source_url") or "")
    row["canonical_url"] = safe_url(row.get("canonical_url") or "")
    return row


def client_ip(handler: BaseHTTPRequestHandler) -> str:
    forwarded = handler.headers.get("X-Forwarded-For", "").split(",")[0].strip()
    if forwarded:
        return forwarded
    real_ip = handler.headers.get("X-Real-IP", "").strip()
    if real_ip:
        return real_ip
    return handler.client_address[0]


def callback_secret() -> str:
    return (
        os.environ.get("ADMIN_TELEGRAM_CALLBACK_TOKEN", "").strip()
        or os.environ.get("TELEGRAM_WEBHOOK_SECRET", "").strip()
        or os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
    )


def callback_signature(session_id: int, action: str) -> str:
    secret = callback_secret()
    if not secret:
        return ""
    digest = hmac.new(secret.encode("utf-8"), f"{session_id}:{action}".encode("utf-8"), hashlib.sha256).digest()
    return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")[:24]


def build_callback_data(session_id: int, action: str) -> str:
    return f"admin_auth:{action}:{session_id}:{callback_signature(session_id, action)}"


def parse_callback_data(data: str) -> tuple[str, int, str] | None:
    parts = data.split(":")
    if len(parts) != 4 or parts[0] != "admin_auth":
        return None
    action = parts[1]
    if action not in {"approve", "reject"}:
        return None
    try:
        session_id = int(parts[2])
    except ValueError:
        return None
    return action, session_id, parts[3]


def verify_callback_secret(handler: BaseHTTPRequestHandler, parsed_url) -> bool:
    secret = os.environ.get("ADMIN_TELEGRAM_CALLBACK_TOKEN", "").strip() or os.environ.get("TELEGRAM_WEBHOOK_SECRET", "").strip()
    if not secret:
        return True
    query_token = parse_qs(parsed_url.query).get("token", [""])[0]
    header_token = handler.headers.get("X-Telegram-Bot-Api-Secret-Token", "") or handler.headers.get("X-Admin-Telegram-Secret", "")
    return hmac.compare_digest(secret, query_token) or hmac.compare_digest(secret, header_token)


def telegram_api(method: str, payload: dict[str, Any]) -> dict[str, Any]:
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
    if not token:
        return {"ok": False, "description": "Telegram Bot Token이 설정되어 있지 않습니다."}
    request = Request(
        f"https://api.telegram.org/bot{token}/{method}",
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(request, timeout=15) as response:
            return json.loads(response.read().decode("utf-8", errors="replace"))
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        try:
            payload = json.loads(detail)
            return {"ok": False, "description": payload.get("description") or "Telegram 요청 전송에 실패했습니다."}
        except json.JSONDecodeError:
            return {"ok": False, "description": f"Telegram 요청 전송에 실패했습니다. HTTP {exc.code}"}
    except URLError:
        return {"ok": False, "description": "Telegram 서버에 연결할 수 없습니다."}
    except Exception:
        return {"ok": False, "description": "Telegram 요청 전송에 실패했습니다."}


def telegram_admin_chat_id() -> str:
    return os.environ.get("TELEGRAM_OWNER_CHAT_ID", "").strip() or os.environ.get("TELEGRAM_CHAT_ID", "").strip()


def telegram_owner_user_id() -> str:
    return os.environ.get("TELEGRAM_OWNER_USER_ID", "").strip()


def send_approval_request(session: dict[str, Any]) -> dict[str, Any]:
    if session.get("telegram_message_id"):
        return {"ok": True, "message_id": int(session["telegram_message_id"]), "error_message": ""}

    chat_id = telegram_admin_chat_id()
    if not chat_id:
        return {"ok": False, "message_id": None, "error_message": "Telegram 관리자 Chat ID가 설정되어 있지 않습니다."}

    session_id = int(session["id"])
    message = "\n".join(
        [
            "관리자 페이지 접속 요청이 있습니다.",
            f"장치 ID: {session['device_id']}",
            f"IP: {session['ip_address']}",
            f"브라우저: {session['user_agent']}",
            "승인하시겠습니까?",
        ]
    )
    payload = {
        "chat_id": chat_id,
        "text": message,
        "reply_markup": {
            "inline_keyboard": [
                [
                    {"text": "승인", "callback_data": build_callback_data(session_id, "approve")},
                    {"text": "거부", "callback_data": build_callback_data(session_id, "reject")},
                ]
            ]
        },
    }
    result = telegram_api("sendMessage", payload)
    if not result.get("ok"):
        return {"ok": False, "message_id": None, "error_message": result.get("description") or "Telegram 승인 메시지 전송에 실패했습니다."}
    message_id = result.get("result", {}).get("message_id")
    if message_id:
        execute_one(
            """
            UPDATE admin.admin_login_session
            SET telegram_message_id = %s, updated_at = CURRENT_TIMESTAMP
            WHERE id = %s
            RETURNING id
            """,
            (message_id, session_id),
        )
    return {"ok": bool(message_id), "message_id": message_id, "error_message": "" if message_id else "Telegram 메시지 ID를 확인할 수 없습니다."}


def apply_telegram_auth_callback(callback_query: dict[str, Any]) -> dict[str, Any]:
    data = str(callback_query.get("data") or "")
    parsed = parse_callback_data(data)
    if not parsed:
        return {"ok": False, "status": None, "message": "처리할 수 없는 승인 요청입니다."}

    action, session_id, signature = parsed
    expected = callback_signature(session_id, action)
    if not expected or not hmac.compare_digest(expected, signature):
        return {"ok": False, "status": None, "message": "승인 요청 검증에 실패했습니다."}

    owner_id = telegram_owner_user_id()
    from_user_id = str((callback_query.get("from") or {}).get("id") or "")
    if owner_id and from_user_id != owner_id:
        return {"ok": False, "status": None, "message": "허가되지 않은 Telegram 사용자입니다."}

    status = APPROVED if action == "approve" else REJECTED
    time_column = "approved_at" if status == APPROVED else "rejected_at"
    row = execute_one(
        f"""
        UPDATE admin.admin_login_session
        SET status = %s,
            {time_column} = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = %s AND status = 'PENDING'
        RETURNING id, status
        """,
        (status, session_id),
    )
    return {
        "ok": True,
        "status": row.get("status", status),
        "message": "승인되었습니다." if status == APPROVED else "거부되었습니다.",
    }


def start_telegram_update_poller() -> None:
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
    chat_id = telegram_admin_chat_id()
    if not token or not chat_id:
        print("[telegram] TELEGRAM_BOT_TOKEN 또는 TELEGRAM_OWNER_CHAT_ID/TELEGRAM_CHAT_ID가 없어 승인 폴링을 건너뜁니다.", flush=True)
        return

    def poll() -> None:
        offset = 0
        telegram_api("deleteWebhook", {"drop_pending_updates": False})
        print("[telegram] 관리자 승인 버튼 폴링을 시작합니다.", flush=True)
        while True:
            result = telegram_api("getUpdates", {"offset": offset, "timeout": 25, "allowed_updates": ["callback_query"]})
            if not result.get("ok"):
                time.sleep(5)
                continue
            for update in result.get("result", []):
                offset = max(offset, int(update.get("update_id", 0)) + 1)
                callback_query = update.get("callback_query")
                if not callback_query:
                    continue
                callback_result = apply_telegram_auth_callback(callback_query)
                callback_id = callback_query.get("id")
                if callback_id:
                    telegram_api(
                        "answerCallbackQuery",
                        {"callback_query_id": callback_id, "text": callback_result.get("message") or "처리되었습니다."},
                    )

    thread = threading.Thread(target=poll, name="telegram-admin-auth-poller", daemon=True)
    thread.start()


def find_approved_session(device_id: str, ip_address: str, user_agent: str) -> dict[str, Any]:
    return fetch_one(
        """
        UPDATE admin.admin_login_session
        SET last_seen_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
        WHERE id = (
            SELECT id
            FROM admin.admin_login_session
            WHERE device_id = %s AND ip_address = %s AND user_agent = %s AND status = 'APPROVED'
            ORDER BY approved_at DESC NULLS LAST, id DESC
            LIMIT 1
        )
        RETURNING id, device_id, ip_address, user_agent, status, telegram_message_id,
                  requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
        """,
        (device_id, ip_address, user_agent),
    )


def find_or_create_pending_session(device_id: str, ip_address: str, user_agent: str) -> dict[str, Any]:
    execute_one(
        """
        UPDATE admin.admin_login_session
        SET status = 'LOGGED_OUT',
            logged_out_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE device_id = %s
          AND ip_address = %s
          AND user_agent = %s
          AND status = 'PENDING'
          AND requested_at < CURRENT_TIMESTAMP - (%s || ' minutes')::interval
        RETURNING id
        """,
        (device_id, ip_address, user_agent, PENDING_TIMEOUT_MINUTES),
    )
    pending = fetch_one(
        """
        SELECT id, device_id, ip_address, user_agent, status, telegram_message_id,
               requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
        FROM admin.admin_login_session
        WHERE device_id = %s AND ip_address = %s AND user_agent = %s AND status = 'PENDING'
        ORDER BY requested_at DESC, id DESC
        LIMIT 1
        """,
        (device_id, ip_address, user_agent),
    )
    if pending:
        return pending
    return execute_one(
        """
        INSERT INTO admin.admin_login_session(device_id, ip_address, user_agent, status, requested_at, last_seen_at)
        VALUES (%s, %s, %s, 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        RETURNING id, device_id, ip_address, user_agent, status, telegram_message_id,
                  requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
        """,
        (device_id, ip_address, user_agent),
    )


def invalidate_login_sessions(device_id: str, ip_address: str, user_agent: str) -> None:
    execute_one(
        """
        UPDATE admin.admin_login_session
        SET status = 'LOGGED_OUT',
            logged_out_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE device_id = %s
          AND ip_address = %s
          AND user_agent = %s
          AND status IN ('APPROVED', 'PENDING')
        RETURNING id
        """,
        (device_id, ip_address, user_agent),
    )


def session_status(session_id: int) -> dict[str, Any]:
    execute_one(
        """
        UPDATE admin.admin_login_session
        SET status = 'LOGGED_OUT',
            logged_out_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = %s
          AND status = 'PENDING'
          AND requested_at < CURRENT_TIMESTAMP - (%s || ' minutes')::interval
        RETURNING id
        """,
        (session_id, PENDING_TIMEOUT_MINUTES),
    )
    return fetch_one(
        """
        SELECT id, device_id, ip_address, user_agent, status,
               requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
        FROM admin.admin_login_session
        WHERE id = %s
        """,
        (session_id,),
    )


def module_rows() -> list[dict[str, Any]]:
    return fetch_all(
        """
        SELECT module_key, module_group, module_name, description, is_enabled, is_required, run_order
        FROM admin.module_config
        ORDER BY run_order, module_key
        """
    )


def dashboard_summary() -> dict[str, Any]:
    today_cycle_id = datetime.now(timezone(timedelta(hours=9))).strftime("%Y-%m-%d")
    candidate_counts = fetch_one(
        """
        SELECT
            COUNT(*)::int AS candidate_count,
            COUNT(*) FILTER (
                WHERE publish_cycle_id = %s
                  AND publish_status = 'READY_TO_PUBLISH'
                  AND COALESCE(post_expired, FALSE) = FALSE
                  AND published_at IS NULL
            )::int AS today_ready_count,
            COUNT(*) FILTER (
                WHERE publish_cycle_id < %s
                  AND publish_status = 'POST_EXPIRED'
            )::int AS previous_post_expired_count,
            COUNT(*) FILTER (
                WHERE publish_status IN ('POSTED', 'PUBLISHED', 'DRY_RUN_PUBLISHED', 'NOTIFIED', 'DRY_RUN_NOTIFIED')
                   OR status IN ('POSTED', 'PUBLISHED', 'DRY_RUN_PUBLISHED', 'NOTIFIED', 'DRY_RUN_NOTIFIED')
            )::int AS published_count,
            COUNT(*) FILTER (
                WHERE COALESCE(post_expired, FALSE) = TRUE
                   OR publish_status = 'POST_EXPIRED'
            )::int AS post_expired_count,
            COUNT(*) FILTER (WHERE status = 'DUPLICATE')::int AS duplicate_count,
            COUNT(*) FILTER (WHERE status = 'FAILED' OR publish_status IN ('FAILED', 'FAILED_RETRYABLE', 'FAILED_REPOST_REQUIRED', 'FAILED_PERMISSION'))::int AS failed_count
        FROM social_news.candidate
        """,
        (today_cycle_id, today_cycle_id),
    )
    publish_metrics = fetch_one(
        """
        SELECT
            COUNT(*) FILTER (WHERE publish_cycle_id = %s)::int AS today_article_count,
            COUNT(*) FILTER (
                WHERE publish_cycle_id = %s
                  AND COALESCE(post_expired, FALSE) = FALSE
                  AND published_at IS NULL
                  AND COALESCE(facebook_post_url, '') = ''
                  AND COALESCE(publish_status, '') NOT IN ('POSTED', 'PUBLISHED', 'NOTIFIED', 'POST_EXPIRED', 'ARCHIVED', 'AUTO_RETRY_BLOCKED')
            )::int AS today_unposted_count,
            ROUND(AVG(evaluation_score) FILTER (WHERE publish_cycle_id = %s AND evaluation_score > 0), 2) AS avg_score,
            COUNT(*) FILTER (
                WHERE publish_cycle_id = %s
                  AND publish_status = 'READY_TO_PUBLISH'
                  AND COALESCE(post_expired, FALSE) = FALSE
                  AND published_at IS NULL
            )::int AS ready_count,
            COUNT(*) FILTER (
                WHERE publish_cycle_id = %s
                  AND publish_status = 'FAILED_RETRYABLE'
                  AND COALESCE(post_expired, FALSE) = FALSE
                  AND published_at IS NULL
            )::int AS retryable_count,
            COUNT(*) FILTER (
                WHERE publish_cycle_id = %s
                  AND publish_status IN ('POSTED', 'PUBLISHED', 'NOTIFIED', 'DRY_RUN_PUBLISHED', 'DRY_RUN_NOTIFIED')
            )::int AS posted_today_count
        FROM social_news.candidate
        """,
        (today_cycle_id, today_cycle_id, today_cycle_id, today_cycle_id, today_cycle_id, today_cycle_id),
    )
    cooldown = NewsPipeline(repository=news_repository(), collectors=[]).publish_cooldown_info()
    module_counts = fetch_one(
        """
        SELECT
            COUNT(*)::int AS module_count,
            COUNT(*) FILTER (WHERE is_enabled)::int AS enabled_module_count,
            COUNT(*) FILTER (WHERE NOT is_enabled)::int AS disabled_module_count
        FROM admin.module_config
        """
    )
    latest_cycle = fetch_one(
        """
        SELECT status, dry_run, started_at, ended_at
        FROM social_news.pipeline_cycle
        ORDER BY started_at DESC
        LIMIT 1
        """
    )
    return {
        **candidate_counts,
        **publish_metrics,
        **module_counts,
        "current_threshold": 50,
        "cooldown": cooldown,
        "cooldown_active": cooldown.get("active", False),
        "next_publish_at": cooldown.get("next_publish_at", ""),
        "latest_cycle": latest_cycle or None,
        "api_connected": True,
        "database": "foreign_worker_job_info",
    }


def candidate_rows(query: dict[str, list[str]] | None = None) -> dict[str, Any]:
    query = query or {}
    page = clamp_query_int(query, "page", 1, minimum=1, maximum=100000)
    size = clamp_query_int(query, "size", 10, minimum=1, maximum=100)
    include_duplicates = str(query.get("includeDuplicates", ["false"])[0]).lower() in {"1", "true", "yes", "on"}
    status = str(query.get("status", [""])[0]).strip()
    search = str(query.get("search", [""])[0]).strip()
    offset = (page - 1) * size
    where = []
    params: list[Any] = []
    if not include_duplicates:
        where.append("COALESCE(is_representative, TRUE) = TRUE")
    if status:
        where.append("(status = %s OR publish_status = %s)")
        params.extend([status, status])
    if search:
        where.append(
            """
            (
                title ILIKE %s OR source_name ILIKE %s OR source_type ILIKE %s
                OR source_url ILIKE %s OR similarity_key ILIKE %s
            )
            """
        )
        term = f"%{search}%"
        params.extend([term, term, term, term, term])
    where_sql = f"WHERE {' AND '.join(where)}" if where else ""
    total = fetch_one(f"SELECT COUNT(*)::int AS total_count FROM social_news.candidate {where_sql}", tuple(params)).get("total_count", 0)
    rows = fetch_all(
        f"""
        SELECT id, category, 'KR' AS region, title, source_name, source_type, source_url, canonical_url,
               google_news_url, publisher_name, evaluation_score,
               duplicate_risk_score, status, publish_status, short_summary, selection_reason, skip_reason, fail_reason,
               collected_at, facebook_post_url, facebook_post_id, publish_cycle_id AS cycle_id,
               post_expired, post_expired_at, post_expired_reason, image_url,
               related_source_count, duplicate_count, group_item_count, last_seen_at, is_representative,
               representative_candidate_id, content_fetch_status, content_fetch_error,
               normalized_item_id, similarity_key
        FROM social_news.candidate
        {where_sql}
        ORDER BY COALESCE(last_seen_at, collected_at) DESC, id DESC
        LIMIT %s OFFSET %s
        """,
        tuple(params + [size, offset]),
    )
    return {"items": [sanitize_news_url_fields(row) for row in rows], "total_count": total, "page": page, "size": size}


def candidate_detail(candidate_id: int) -> dict[str, Any]:
    candidate = fetch_one(
        """
        SELECT id, category, 'KR' AS region, title, source_name, source_type, source_url, canonical_url,
               google_news_url, publisher_name, generated_title, generated_summary_en, generated_why_it_matters_en,
               summary, content, image_url, image_urls_json, language, keyword, hash_key, similarity_key,
               evaluation_score, duplicate_risk_score, foreign_worker_relevance_score, korea_relevance_score,
               visa_or_labor_policy_score, freshness_score, source_reliability_score, facebook_post_suitability_score,
               status, publish_status, short_summary, key_points, relevance_reason, risk_notes,
               selection_reason, skip_reason, fail_reason, score_threshold, score_breakdown_json,
               collected_at, published_at, facebook_post_url, facebook_post_id, publish_cycle_id AS cycle_id,
               post_expired, post_expired_at, post_expired_reason, telegram_notified, publish_attempt_count,
               last_publish_attempt_at, normalized_item_id, related_source_count, duplicate_count, group_item_count,
               last_seen_at, is_representative, representative_candidate_id, content_fetch_status, content_fetch_error
        FROM social_news.candidate
        WHERE id = %s
        """,
        (candidate_id,),
    )
    if not candidate:
        return {}
    sanitize_news_url_fields(candidate)
    repo_candidate = news_repository().get_candidate(candidate_id)
    facebook_message = FacebookPublisher().build_message(repo_candidate) if repo_candidate else ""
    normalized_item_id = candidate.get("normalized_item_id")
    group_items = []
    raw_items = []
    if normalized_item_id:
        group_items = fetch_all(
            """
            SELECT id, title, source_name, source_type, source_url, canonical_url, google_news_url,
                   status, publish_status, evaluation_score, collected_at, facebook_post_url,
                   is_representative, duplicate_count, related_source_count
                   , representative_candidate_id, content_fetch_status
            FROM social_news.candidate
            WHERE normalized_item_id = %s
            ORDER BY COALESCE(last_seen_at, collected_at) DESC, id DESC
            LIMIT 200
            """,
            (normalized_item_id,),
        )
        raw_items = fetch_all(
            """
            SELECT id, source_type, source_name, publisher_name, source_url, google_news_url,
                   raw_title AS title, language, is_duplicate, duplicate_reason, collected_at
            FROM social_news.raw_item
            WHERE normalized_item_id = %s
            ORDER BY collected_at DESC, id DESC
            LIMIT 200
            """,
            (normalized_item_id,),
        )
    group_items = [sanitize_news_url_fields(item) for item in group_items]
    raw_items = [sanitize_news_url_fields(item) for item in raw_items]
    return {
        "candidate": candidate,
        "facebookMessage": facebook_message,
        "groupItems": group_items,
        "rawItems": raw_items,
        "publishLogs": fetch_all(
            """
            SELECT id, channel, page_id, external_post_id, dry_run, status, error_code, error_message,
                   published_at, facebook_permalink, score, threshold, message_preview, response_code, response_body
            FROM social_news.publish_log
            WHERE news_candidate_id = %s
            ORDER BY published_at DESC, id DESC
            LIMIT 20
            """,
            (candidate_id,),
        ),
        "telegramLogs": fetch_all(
            """
            SELECT id, dry_run, message, status, error_message, sent_at
            FROM social_news.telegram_notify_log
            WHERE news_candidate_id = %s
            ORDER BY sent_at DESC, id DESC
            LIMIT 20
            """,
            (candidate_id,),
        ),
        "pipelineLogs": fetch_all(
            """
            SELECT id, step_name, status, COALESCE(message, skipped_reason, '') AS message,
                   payload_json::text AS payload_json, created_at
            FROM social_news.pipeline_step_log
            WHERE news_candidate_id = %s
            ORDER BY created_at DESC, id DESC
            LIMIT 50
            """,
            (candidate_id,),
        ),
    }


def delete_candidate_rows(ids: list[int]) -> int:
    deleted = news_repository().delete_candidates(ids)
    write_bot_log("candidate_delete", "COMPLETED", f"후보 기사 {deleted}건 삭제")
    return deleted


def cleanup_candidate_article_data(payload: dict[str, Any]) -> dict[str, Any]:
    ids = payload.get("ids") if isinstance(payload, dict) else []
    selected_ids = [int(item) for item in ids if str(item).isdigit()] if isinstance(ids, list) else []
    limit = int(payload.get("limit") or 50) if isinstance(payload, dict) else 50
    limit = max(1, min(limit, 100))
    rows = cleanup_candidate_targets(payload, selected_ids, limit)
    result = {"target": len(rows), "updated": 0, "resolved_url": 0, "content_updated": 0, "score_updated": 0, "failed": 0, "skipped": 0}
    for row in rows:
        updated = cleanup_single_candidate(row)
        for key in result:
            if key in updated and key != "target":
                result[key] += int(updated[key] or 0)
    news_repository().insert_pipeline_log(
        "article_cleanup",
        "COMPLETED",
        f"기사 링크/본문 정리 완료: 대상 {result['target']}건, 갱신 {result['updated']}건, 실패 {result['failed']}건",
        payload_json=json.dumps(result, ensure_ascii=False),
    )
    return {"ok": True, **result}


def cleanup_candidate_targets(payload: dict[str, Any], selected_ids: list[int], limit: int) -> list[dict[str, Any]]:
    where = []
    params: list[Any] = []
    if selected_ids:
        where.append("id = ANY(%s)")
        params.append(selected_ids)
    else:
        where.append(
            """
            (
                COALESCE(source_url, '') = ''
                OR COALESCE(content, '') = ''
                OR COALESCE(content_fetch_status, '') IN ('FAILED', 'URL_MISSING')
            )
            """
        )
        status = str(payload.get("status") or "").strip()
        search = str(payload.get("search") or "").strip()
        include_duplicates = str(payload.get("includeDuplicates") or "") in {"1", "true", "True"}
        if not include_duplicates:
            where.append("COALESCE(is_representative, TRUE) = TRUE")
        if status:
            where.append("(status = %s OR publish_status = %s)")
            params.extend([status, status])
        if search:
            where.append(
                """
                (
                    title ILIKE %s OR source_name ILIKE %s OR source_type ILIKE %s
                    OR source_url ILIKE %s OR google_news_url ILIKE %s OR similarity_key ILIKE %s
                )
                """
            )
            term = f"%{search}%"
            params.extend([term, term, term, term, term, term])
    return fetch_all(
        f"""
        SELECT id, normalized_item_id, title, source_url, canonical_url, google_news_url,
               content, image_url, image_urls_json, publisher_name, source_name
        FROM social_news.candidate
        WHERE {' AND '.join(where)}
        ORDER BY COALESCE(last_seen_at, collected_at) DESC, id DESC
        LIMIT %s
        """,
        tuple(params + [limit]),
    )


def cleanup_single_candidate(row: dict[str, Any]) -> dict[str, int]:
    candidate_id = int(row["id"])
    source_url = safe_url(row.get("source_url") or "")
    canonical_url = safe_url(row.get("canonical_url") or "")
    google_news_url = str(row.get("google_news_url") or "").strip()
    result = {"updated": 0, "resolved_url": 0, "content_updated": 0, "score_updated": 0, "failed": 0, "skipped": 0}

    if not source_url:
        sibling_url = find_existing_article_url(row)
        if sibling_url:
            source_url = sibling_url
            canonical_url = canonical_url or sibling_url
            result["resolved_url"] = 1

    if not source_url and google_news_url:
        resolved_url = resolve_google_news_url(google_news_url, timeout=10)
        if is_acceptable_source_url(resolved_url):
            source_url = resolved_url
            canonical_url = canonical_url or resolved_url
            result["resolved_url"] = 1

    metadata = None
    content = str(row.get("content") or "")
    content_status = "URL_MISSING"
    content_error = ""
    if source_url:
        try:
            metadata = fetch_article_metadata(source_url, timeout=12)
            if metadata.canonical_url and is_acceptable_source_url(metadata.canonical_url):
                canonical_url = metadata.canonical_url
                source_url = metadata.canonical_url
            if metadata.content and len(metadata.content) >= 120:
                content = metadata.content
                result["content_updated"] = 1
                content_status = "FETCHED"
            else:
                content_status = "FAILED"
                content_error = "content too short"
        except Exception as exc:
            content_status = "FAILED"
            content_error = str(exc)[:300]
    score_payload = score_cleanup_candidate(candidate_id, source_url, canonical_url, content)
    if score_payload:
        result["score_updated"] = 1

    if not source_url or content_status == "FAILED":
        result["failed"] = 1
    else:
        result["updated"] = 1

    image_url = (metadata.image_url if metadata and metadata.image_url else row.get("image_url") or "").strip()
    image_urls = metadata.image_urls if metadata and metadata.image_urls else row.get("image_urls_json") or []
    publisher_name = metadata.publisher_name if metadata and metadata.publisher_name else row.get("publisher_name") or row.get("source_name") or ""
    update_cleanup_rows(
        candidate_id=candidate_id,
        normalized_item_id=row.get("normalized_item_id"),
        source_url=source_url,
        canonical_url=canonical_url,
        google_news_url=google_news_url,
        content=content,
        image_url=image_url,
        image_urls=image_urls,
        publisher_name=publisher_name,
        content_fetch_status=content_status,
        content_fetch_error=content_error,
        score_payload=score_payload,
    )
    return result


def find_existing_article_url(row: dict[str, Any]) -> str:
    title = str(row.get("title") or "").strip()
    normalized_item_id = row.get("normalized_item_id")
    source_name = str(row.get("source_name") or row.get("publisher_name") or "").strip()
    clauses = ["id <> %s", "COALESCE(source_url, '') <> ''"]
    params: list[Any] = [int(row["id"])]
    if normalized_item_id and title:
        clauses.append("(normalized_item_id = %s OR title = %s)")
        params.extend([normalized_item_id, title])
    elif normalized_item_id:
        clauses.append("normalized_item_id = %s")
        params.append(normalized_item_id)
    elif title:
        clauses.append("title = %s")
        params.append(title)
    if source_name:
        clauses.append("(source_name = %s OR publisher_name = %s)")
        params.extend([source_name, source_name])
    candidates = fetch_all(
        f"""
        SELECT source_url, canonical_url, content
        FROM social_news.candidate
        WHERE {' AND '.join(clauses)}
        ORDER BY
            CASE WHEN COALESCE(content, '') <> '' THEN 0 ELSE 1 END,
            COALESCE(last_seen_at, collected_at) DESC,
            id DESC
        LIMIT 10
        """,
        tuple(params),
    )
    for candidate in candidates:
        for value in (candidate.get("canonical_url"), candidate.get("source_url")):
            url = safe_url(value or "")
            if url:
                return url
    return ""


def score_cleanup_candidate(candidate_id: int, source_url: str, canonical_url: str, content: str) -> dict[str, Any]:
    candidate = news_repository().get_candidate(candidate_id)
    if not candidate:
        return {}
    candidate.source_url = source_url
    candidate.canonical_url = canonical_url
    candidate.content = content or candidate.content
    evaluation = CandidateEvaluator().evaluate(candidate, threshold=40.0)
    return {
        "evaluation_score": evaluation.total_score,
        "duplicate_risk_score": evaluation.duplicate_risk_score,
        "foreign_worker_relevance_score": evaluation.foreign_worker_relevance_score,
        "korea_relevance_score": evaluation.korea_relevance_score,
        "visa_or_labor_policy_score": evaluation.visa_or_labor_policy_score,
        "freshness_score": evaluation.freshness_score,
        "source_reliability_score": evaluation.source_reliability_score,
        "facebook_post_suitability_score": evaluation.facebook_post_suitability_score,
        "score_threshold": evaluation.threshold,
        "score_breakdown_json": evaluation.score_breakdown_json,
        "risk_level": "HIGH" if evaluation.duplicate_risk_score >= 0.85 else "LOW",
        "decision": evaluation.decision,
        "selection_reason": evaluation.reason if evaluation.decision == "READY_TO_PUBLISH" else "",
        "skip_reason": evaluation.reason if evaluation.decision != "READY_TO_PUBLISH" else "",
    }


def update_cleanup_rows(
    *,
    candidate_id: int,
    normalized_item_id: Any,
    source_url: str,
    canonical_url: str,
    google_news_url: str,
    content: str,
    image_url: str,
    image_urls: Any,
    publisher_name: str,
    content_fetch_status: str,
    content_fetch_error: str,
    score_payload: dict[str, Any],
) -> None:
    image_urls_json = json.dumps(image_urls or [], ensure_ascii=False) if not isinstance(image_urls, str) else image_urls
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE social_news.candidate
                SET source_url = %s,
                    canonical_url = %s,
                    content = %s,
                    image_url = COALESCE(NULLIF(%s, ''), image_url),
                    image_urls_json = %s::jsonb,
                    publisher_name = COALESCE(NULLIF(%s, ''), publisher_name),
                    content_fetch_status = %s,
                    content_fetch_error = %s,
                    evaluation_score = COALESCE(%s, evaluation_score),
                    duplicate_risk_score = COALESCE(%s, duplicate_risk_score),
                    foreign_worker_relevance_score = COALESCE(%s, foreign_worker_relevance_score),
                    korea_relevance_score = COALESCE(%s, korea_relevance_score),
                    visa_or_labor_policy_score = COALESCE(%s, visa_or_labor_policy_score),
                    freshness_score = COALESCE(%s, freshness_score),
                    source_reliability_score = COALESCE(%s, source_reliability_score),
                    facebook_post_suitability_score = COALESCE(%s, facebook_post_suitability_score),
                    score_threshold = COALESCE(%s, score_threshold),
                    score_breakdown_json = COALESCE(%s, score_breakdown_json),
                    risk_level = COALESCE(NULLIF(%s, ''), risk_level),
                    selection_reason = COALESCE(NULLIF(%s, ''), selection_reason),
                    skip_reason = COALESCE(NULLIF(%s, ''), skip_reason),
                    status = CASE
                        WHEN status IN ('TEXT_INVALID', 'CANDIDATE', 'NORMALIZED', 'SUMMARIZED', 'SCORED', 'SKIPPED') THEN COALESCE(NULLIF(%s, ''), status)
                        ELSE status
                    END,
                    publish_status = CASE
                        WHEN publish_status IN ('TEXT_INVALID', 'CANDIDATE', 'NORMALIZED', 'SUMMARIZED', 'SCORED', 'SKIPPED') THEN COALESCE(NULLIF(%s, ''), publish_status)
                        ELSE publish_status
                    END,
                    updated_at = CURRENT_TIMESTAMP
                WHERE id = %s
                """,
                (
                    source_url,
                    canonical_url,
                    content,
                    image_url,
                    image_urls_json,
                    publisher_name,
                    content_fetch_status,
                    content_fetch_error,
                    score_payload.get("evaluation_score"),
                    score_payload.get("duplicate_risk_score"),
                    score_payload.get("foreign_worker_relevance_score"),
                    score_payload.get("korea_relevance_score"),
                    score_payload.get("visa_or_labor_policy_score"),
                    score_payload.get("freshness_score"),
                    score_payload.get("source_reliability_score"),
                    score_payload.get("facebook_post_suitability_score"),
                    score_payload.get("score_threshold"),
                    score_payload.get("score_breakdown_json"),
                    score_payload.get("risk_level", ""),
                    score_payload.get("selection_reason", ""),
                    score_payload.get("skip_reason", ""),
                    score_payload.get("decision", ""),
                    score_payload.get("decision", ""),
                    candidate_id,
                ),
            )
            if normalized_item_id:
                cur.execute(
                    """
                    UPDATE social_news.normalized_item
                    SET source_url = %s,
                        canonical_url = %s,
                        content = %s,
                        image_url = COALESCE(NULLIF(%s, ''), image_url),
                        image_urls_json = %s::jsonb,
                        publisher_name = COALESCE(NULLIF(%s, ''), publisher_name),
                        content_fetch_status = %s,
                        content_fetch_error = %s,
                        normalized_at = CURRENT_TIMESTAMP
                    WHERE id = %s
                    """,
                    (source_url, canonical_url, content, image_url, image_urls_json, publisher_name, content_fetch_status, content_fetch_error, normalized_item_id),
                )
                cur.execute(
                    """
                    UPDATE social_news.raw_item
                    SET source_url = %s,
                        raw_content = COALESCE(NULLIF(%s, ''), raw_content),
                        publisher_name = COALESCE(NULLIF(%s, ''), publisher_name),
                        content_fetch_status = %s,
                        content_fetch_error = %s
                    WHERE normalized_item_id = %s
                       OR (COALESCE(google_news_url, '') <> '' AND google_news_url = %s)
                    """,
                    (source_url, content, publisher_name, content_fetch_status, content_fetch_error, normalized_item_id, google_news_url),
                )
        conn.commit()


def repost_candidate(candidate_id: int) -> dict[str, Any]:
    repository = news_repository()
    candidate = repository.get_candidate(candidate_id)
    if candidate is None:
        return {"ok": False, "message": "재게시할 뉴스를 찾을 수 없습니다."}
    if not (candidate.source_url or candidate.canonical_url or candidate.google_news_url):
        return {"ok": False, "message": "원문 URL이 없어 재게시할 수 없습니다."}

    cycle_id = today_cycle_id()
    candidate.selection_reason = "관리자 재게시 요청으로 즉시 Facebook 게시를 시도했습니다."
    candidate.skip_reason = ""
    candidate.fail_reason = ""
    candidate.post_expired = False
    candidate.post_expired_reason = ""
    candidate.cycle_id = cycle_id
    candidate.status = "READY_TO_PUBLISH"
    candidate.publish_status = "READY_TO_PUBLISH"
    repository.update_candidate(candidate)
    repository.insert_pipeline_log("facebook_repost", "STARTED", f"관리자 재게시 시도: {candidate.title}", candidate.id)

    result = NewsPipeline(repository=repository, collectors=[]).auto_publish(candidate, dry_run=False)
    refreshed = repository.get_candidate(candidate_id)
    ok = result.get("facebook_status") == "PUBLISHED"
    repository.insert_pipeline_log(
        "facebook_repost",
        "COMPLETED" if ok else "FAILED",
        f"관리자 재게시 {'완료' if ok else '실패'}: {candidate.title}",
        candidate.id,
    )
    return {
        "ok": ok,
        "message": "재게시가 완료되었습니다." if ok else result.get("error_message") or "재게시가 실패했습니다.",
        "result": result,
        "candidate": refreshed.to_dict() if refreshed else None,
    }


def log_rows(limit: int = 50, offset: int = 0) -> list[dict[str, Any]]:
    logs = news_repository().list_pipeline_logs(limit=limit, offset=offset)
    return [
        {
            "id": str(row["id"]),
            "bot": "소셜 뉴스 봇",
            "level": "ERROR" if row["status"] == "FAILED" else "WARN" if row["status"] in {"SKIPPED", "WAITING"} else "INFO",
            "message": row["message"],
            "time": row["created_at"],
            "latency": row["step"],
        }
        for row in logs
    ]


class AdminRequestHandler(BaseHTTPRequestHandler):
    def do_OPTIONS(self) -> None:
        self.send_response(204)
        self._send_common_headers()
        self.end_headers()

    def do_GET(self) -> None:
        try:
            parsed_url = urlparse(self.path)
            path = parsed_url.path
            query = parse_qs(parsed_url.query)
            if not self._is_public_get(path) and not self._has_approved_cookie():
                self._send_json({"error": "unauthorized", "message": "관리자 승인이 필요합니다."}, status=401)
                return

            if path == "/api/health":
                self._send_json({"ok": True, "database": "foreign_worker_job_info"})
            elif path.startswith("/api/admin/auth/status/"):
                self._handle_auth_status(path)
            elif path == "/api/admin/modules":
                self._send_json({"items": module_rows()})
            elif path == "/api/dashboard/summary":
                self._send_json(dashboard_summary())
            elif path == "/api/social/news/candidates":
                self._send_json(candidate_rows(query))
            elif path.startswith("/api/social/news/candidates/"):
                raw_id = path.rsplit("/", 1)[-1]
                if not raw_id.isdigit():
                    self._send_json({"error": "bad_request", "message": "뉴스 ID가 올바르지 않습니다."}, status=400)
                    return
                detail = candidate_detail(int(raw_id))
                if not detail:
                    self._send_json({"error": "not_found", "message": "뉴스 상세 데이터를 찾을 수 없습니다."}, status=404)
                    return
                self._send_json(detail)
            elif path == "/api/logs/recent":
                limit = clamp_query_int(query, "limit", 50, minimum=1, maximum=100)
                offset = clamp_query_int(query, "offset", 0, minimum=0, maximum=10000)
                self._send_json({"items": log_rows(limit=limit, offset=offset)})
            elif path == "/api/admin/bot/status":
                self._send_json(format_bot_status(bot_runtime_row()))
            elif path == "/api/admin/llama/status":
                self._send_json(ensure_llama(start_command=False))
            elif path == "/api/admin/job-collector/status":
                self._send_json(job_collector_status())
            elif path == "/api/admin/job-collector/logs":
                limit = clamp_query_int(query, "limit", 50, minimum=1, maximum=100)
                offset = clamp_query_int(query, "offset", 0, minimum=0, maximum=10000)
                self._send_json({"items": job_collector_logs(limit=limit, offset=offset)})
            elif path == "/api/admin/job-postings":
                self._send_json({"items": job_posting_rows()})
            elif path == "/api/admin/occupation/dashboard":
                self._send_json(occupation_dashboard())
            elif path == "/api/admin/occupation/jobs":
                self._send_json(occupation_job_rows(query))
            elif path.startswith("/api/admin/occupation/jobs/"):
                raw_id = path.rsplit("/", 1)[-1]
                if not raw_id.isdigit():
                    self._send_json({"error": "bad_request", "message": "직무정보 ID가 올바르지 않습니다."}, status=400)
                    return
                detail = occupation_job_detail(int(raw_id))
                self._send_json(detail if detail else {"error": "not_found", "message": "직무정보를 찾을 수 없습니다."}, status=200 if detail else 404)
            elif path == "/api/admin/occupation/occupations":
                self._send_json(occupation_rows(query))
            elif path.startswith("/api/admin/occupation/occupations/"):
                raw_id = path.rsplit("/", 1)[-1]
                if not raw_id.isdigit():
                    self._send_json({"error": "bad_request", "message": "직업정보 ID가 올바르지 않습니다."}, status=400)
                    return
                detail = occupation_detail(int(raw_id))
                self._send_json(detail if detail else {"error": "not_found", "message": "직업정보를 찾을 수 없습니다."}, status=200 if detail else 404)
            elif path == "/api/admin/occupation/keyword-mappings":
                self._send_json(occupation_keyword_rows(query))
            elif path == "/api/admin/occupation/collect-logs":
                self._send_json({"items": occupation_collect_logs(query)})
            else:
                self._send_json({"error": "not_found", "message": "요청한 API를 찾을 수 없습니다."}, status=404)
        except Exception:
            self._send_json({"error": "server_error", "message": "서버 처리 중 오류가 발생했습니다."}, status=500)

    def do_POST(self) -> None:
        parsed_url = urlparse(self.path)
        path = parsed_url.path
        try:
            if path not in PUBLIC_POST_PATHS and not self._has_approved_cookie():
                self._send_json({"error": "unauthorized", "message": "관리자 승인이 필요합니다."}, status=401)
                return

            if path == "/api/admin/auth/check":
                self._handle_auth_check()
            elif path == "/api/admin/auth/logout":
                self._handle_logout()
            elif path == "/api/admin/telegram/callback":
                self._handle_telegram_callback(parsed_url)
            elif path == "/api/admin/bot/start":
                self._send_json(start_bot())
            elif path == "/api/admin/bot/stop":
                self._send_json(stop_bot())
            elif path == "/api/admin/bot/reset-error":
                self._send_json(reset_bot_error())
            elif path == "/api/admin/llama/reconnect":
                self._send_json(ensure_llama(start_command=True))
            elif path == "/api/admin/llama/start":
                self._send_json(ensure_llama(start_command=True))
            elif path == "/api/admin/llama/stop":
                self._send_json(stop_llama())
            elif path == "/api/social/news/candidates/delete":
                payload = self._read_json()
                ids = payload.get("ids") if isinstance(payload, dict) else []
                if not isinstance(ids, list):
                    self._send_json({"error": "bad_request", "message": "삭제할 항목을 선택해주세요."}, status=400)
                    return
                deleted = delete_candidate_rows([int(item) for item in ids if str(item).isdigit()])
                self._send_json({"deleted": deleted})
            elif path == "/api/social/news/candidates/repost":
                payload = self._read_json()
                candidate_id = int(payload.get("id") or 0) if isinstance(payload, dict) else 0
                if candidate_id <= 0:
                    self._send_json({"error": "bad_request", "message": "재게시할 뉴스를 선택해주세요."}, status=400)
                    return
                result = repost_candidate(candidate_id)
                self._send_json(result)
            elif path == "/api/social/news/candidates/cleanup-links":
                payload = self._read_json()
                self._send_json(cleanup_candidate_article_data(payload if isinstance(payload, dict) else {}))
            elif path == "/api/admin/occupation/jobs/collect":
                payload = self._read_json()
                self._send_json(run_occupation_job_collection(payload if isinstance(payload, dict) else {}))
            elif path == "/api/admin/occupation/occupations/collect":
                payload = self._read_json()
                self._send_json(run_occupation_info_collection(payload if isinstance(payload, dict) else {}))
            elif path == "/api/admin/occupation/keyword-mappings":
                payload = self._read_json()
                self._send_json(occupation_repository().upsert_keyword_mapping(payload if isinstance(payload, dict) else {}))
            elif path == "/api/admin/occupation/keyword-mappings/generate":
                self._send_json(occupation_repository().generate_keyword_mappings())
            elif path == "/api/admin/job-collector/run":
                self._send_json(start_job_collection(smoke=False))
            elif path == "/api/admin/job-collector/smoke-test":
                self._send_json(start_job_collection(smoke=True))
            elif path == "/api/admin/job-collector/scheduler/start":
                self._send_json(start_job_scheduler())
            elif path == "/api/admin/job-collector/scheduler/stop":
                self._send_json(stop_job_scheduler())
            else:
                self._send_json({"error": "not_found", "message": "요청한 API를 찾을 수 없습니다."}, status=404)
        except Exception:
            self._send_json({"error": "server_error", "message": "서버 처리 중 오류가 발생했습니다."}, status=500)

    def do_PUT(self) -> None:
        path = urlparse(self.path).path
        try:
            if not self._has_approved_cookie():
                self._send_json({"error": "unauthorized", "message": "관리자 승인이 필요합니다."}, status=401)
                return
            if path == "/api/admin/job-collector/settings":
                payload = self._read_json()
                self._send_json({"settings": update_job_collector_settings(payload)})
            elif path.startswith("/api/admin/occupation/keyword-mappings/"):
                raw_id = path.rsplit("/", 1)[-1]
                if not raw_id.isdigit():
                    self._send_json({"error": "bad_request", "message": "검색어 매핑 ID가 올바르지 않습니다."}, status=400)
                    return
                payload = self._read_json()
                self._send_json(occupation_repository().upsert_keyword_mapping(payload if isinstance(payload, dict) else {}, item_id=int(raw_id)))
            else:
                self._send_json({"error": "not_found", "message": "요청한 API를 찾을 수 없습니다."}, status=404)
        except Exception:
            self._send_json({"error": "server_error", "message": "서버 처리 중 오류가 발생했습니다."}, status=500)

    def _is_public_get(self, path: str) -> bool:
        return path in PUBLIC_GET_PATHS or any(path.startswith(prefix) for prefix in PUBLIC_GET_PREFIXES)

    def _read_json(self) -> dict[str, Any]:
        length = int(self.headers.get("Content-Length", "0") or "0")
        if length <= 0:
            return {}
        raw = self.rfile.read(length).decode("utf-8", errors="replace")
        return json.loads(raw) if raw else {}

    def _cookie_session_id(self) -> int | None:
        raw_cookie = self.headers.get("Cookie", "")
        jar = cookies.SimpleCookie()
        jar.load(raw_cookie)
        morsel = jar.get(SESSION_COOKIE)
        if not morsel:
            return None
        try:
            return int(morsel.value)
        except ValueError:
            return None

    def _has_approved_cookie(self) -> bool:
        session_id = self._cookie_session_id()
        device_id = self.headers.get("X-Device-Id", "").strip()
        user_agent = self.headers.get("User-Agent", "").strip()
        if not device_id or not user_agent:
            return False
        ip_address = client_ip(self)
        if session_id:
            row = fetch_one(
                """
                UPDATE admin.admin_login_session
                SET last_seen_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
                WHERE id = %s
                  AND device_id = %s
                  AND ip_address = %s
                  AND user_agent = %s
                  AND status = 'APPROVED'
                RETURNING id
                """,
                (session_id, device_id, ip_address, user_agent),
            )
            if row:
                return True
        return bool(find_approved_session(device_id, ip_address, user_agent))

    def _handle_auth_check(self) -> None:
        payload = self._read_json()
        device_id = str(payload.get("deviceId") or "").strip()
        user_agent = str(payload.get("userAgent") or self.headers.get("User-Agent") or "").strip()
        force_approval_request = bool(payload.get("forceApprovalRequest"))
        if not device_id or not user_agent:
            self._send_json({"error": "bad_request", "message": "장치 식별값을 확인할 수 없습니다."}, status=400)
            return

        ip_address = client_ip(self)
        if force_approval_request:
            invalidate_login_sessions(device_id, ip_address, user_agent)
        else:
            approved = find_approved_session(device_id, ip_address, user_agent)
            if approved:
                self._send_auth_response(approved)
                return

        pending = find_or_create_pending_session(device_id, ip_address, user_agent)
        send_result = send_approval_request(pending)
        if not send_result.get("ok"):
            self._send_json(
                {
                    "sessionId": pending.get("id"),
                    "status": "ERROR",
                    "approved": False,
                    "message": f"Telegram 승인 메시지 전송에 실패했습니다. {send_result.get('error_message')}",
                },
                status=503,
                set_cookie=pending.get("id"),
            )
            return
        self._send_auth_response(pending)

    def _handle_auth_status(self, path: str) -> None:
        try:
            session_id = int(path.rstrip("/").split("/")[-1])
        except ValueError:
            self._send_json({"error": "bad_request", "message": "세션 정보를 확인할 수 없습니다."}, status=400)
            return
        row = session_status(session_id)
        if not row:
            self._send_json({"error": "not_found", "message": "세션 정보를 찾을 수 없습니다."}, status=404)
            return
        device_id = self.headers.get("X-Device-Id", "").strip()
        user_agent = self.headers.get("User-Agent", "").strip()
        if (
            not device_id
            or not user_agent
            or row.get("device_id") != device_id
            or row.get("ip_address") != client_ip(self)
            or row.get("user_agent") != user_agent
        ):
            self._send_json({"error": "forbidden", "message": "접속 아이디가 허가되지 않습니다."}, status=403)
            return
        if row.get("status") == APPROVED:
            row = execute_one(
                """
                UPDATE admin.admin_login_session
                SET last_seen_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
                WHERE id = %s
                RETURNING id, device_id, ip_address, user_agent, status,
                          requested_at, approved_at, rejected_at, logged_out_at, last_seen_at
                """,
                (session_id,),
            )
        self._send_auth_response(row)

    def _handle_logout(self) -> None:
        session_id = self._cookie_session_id()
        payload = self._read_json()
        device_id = str(payload.get("deviceId") or self.headers.get("X-Device-Id") or "").strip()
        user_agent = str(payload.get("userAgent") or self.headers.get("User-Agent") or "").strip()
        if session_id:
            execute_one(
                """
                UPDATE admin.admin_login_session
                SET status = 'LOGGED_OUT',
                    logged_out_at = CURRENT_TIMESTAMP,
                    updated_at = CURRENT_TIMESTAMP
                WHERE id = %s AND status IN ('APPROVED', 'PENDING')
                RETURNING id
                """,
                (session_id,),
            )
        if device_id and user_agent:
            execute_one(
                """
                UPDATE admin.admin_login_session
                SET status = 'LOGGED_OUT',
                    logged_out_at = CURRENT_TIMESTAMP,
                    updated_at = CURRENT_TIMESTAMP
                WHERE device_id = %s
                  AND ip_address = %s
                  AND user_agent = %s
                  AND status IN ('APPROVED', 'PENDING')
                RETURNING id
                """,
                (device_id, client_ip(self), user_agent),
            )
        self._send_json({"status": LOGGED_OUT, "message": "로그아웃되었습니다."}, clear_cookie=True)

    def _handle_telegram_callback(self, parsed_url) -> None:
        if not verify_callback_secret(self, parsed_url):
            self._send_json({"ok": False, "message": "Callback 검증에 실패했습니다."}, status=403)
            return
        payload = self._read_json()
        callback_query = payload.get("callback_query") or payload
        result = apply_telegram_auth_callback(callback_query)
        callback_id = callback_query.get("id")
        if callback_id:
            telegram_api(
                "answerCallbackQuery",
                {"callback_query_id": callback_id, "text": result.get("message") or "처리되었습니다."},
            )
        self._send_json(result, status=200 if result.get("ok") else 403)

    def _send_auth_response(self, session: dict[str, Any], message: str | None = None) -> None:
        status = session.get("status")
        response_message = message or {
            PENDING: "Telegram에서 접속 승인을 완료해주세요.",
            APPROVED: "접속이 승인되었습니다.",
            REJECTED: "접속이 거부되었습니다.",
            LOGGED_OUT: "승인 요청 시간이 만료되었습니다. 다시 승인 요청을 눌러주세요.",
        }.get(status, "관리자 접속 확인 중입니다.")
        self._send_json(
            {
                "sessionId": session.get("id"),
                "status": status,
                "approved": status == APPROVED,
                "message": response_message,
            },
            set_cookie=session.get("id"),
        )

    def _send_common_headers(self) -> None:
        origin = self.headers.get("Origin", "").strip().rstrip("/")
        if not origin:
            referer = self.headers.get("Referer", "").strip()
            parsed_referer = urlparse(referer)
            if parsed_referer.scheme and parsed_referer.netloc:
                origin = f"{parsed_referer.scheme}://{parsed_referer.netloc}".rstrip("/")
        if origin not in ALLOWED_ADMIN_ORIGINS and origin.startswith("http://localhost:5173"):
            origin = "http://localhost:5173"
        if origin not in ALLOWED_ADMIN_ORIGINS and origin.startswith("http://127.0.0.1:5173"):
            origin = "http://127.0.0.1:5173"
        self.send_header("Access-Control-Allow-Origin", origin if origin in ALLOWED_ADMIN_ORIGINS else "http://127.0.0.1:5173")
        self.send_header("Vary", "Origin")
        self.send_header("Access-Control-Allow-Credentials", "true")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, PUT, OPTIONS")
        self.send_header(
            "Access-Control-Allow-Headers",
            "Content-Type, X-Device-Id, X-Admin-Telegram-Secret, X-Telegram-Bot-Api-Secret-Token",
        )

    def _send_json(
        self,
        payload: dict[str, Any],
        status: int = 200,
        set_cookie: Any = None,
        clear_cookie: bool = False,
    ) -> None:
        body = json.dumps(json_ready(payload), ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self._send_common_headers()
        if clear_cookie:
            self.send_header("Set-Cookie", f"{SESSION_COOKIE}=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax")
        elif set_cookie:
            self.send_header("Set-Cookie", f"{SESSION_COOKIE}={set_cookie}; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax")
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format: str, *args: Any) -> None:
        return


def main(argv: list[str] | None = None) -> int:
    load_env_file()
    parser = argparse.ArgumentParser(description="Run the WorkConnect admin API server.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    args = parser.parse_args(argv)

    ensure_auth_schema()
    ignored_storage_keys = (
        "NEWS_BOT_" + "STORAGE",
        "NEWS_BOT_" + "SQLITE_DB",
        "JOB_COLLECTOR_" + "SQLITE_DB",
    )
    ignored_storage_env = [key for key in ignored_storage_keys if os.environ.get(key)]
    if ignored_storage_env:
        print(f"[storage][WARN] SQLite 저장소 환경변수는 더 이상 사용하지 않아 무시합니다: {', '.join(ignored_storage_env)}", flush=True)
    print(f"[storage] PostgreSQL 연결 사용: {safe_connection_summary()}", flush=True)
    facebook_config = facebook_runtime_config_summary()
    facebook_config_message = (
        f"Facebook runtime config: page_id={facebook_config['page_id'] or '-'}, "
        f"token_env={facebook_config['page_token_env_key']}, "
        f"page_token={facebook_config['page_token_masked'] or '-'}, "
        f"user_token_present={facebook_config['user_token_present']}"
    )
    print(f"[facebook] {facebook_config_message}", flush=True)
    try:
        news_repository().insert_pipeline_log("facebook_config", "COMPLETED", facebook_config_message, payload_json=json.dumps(facebook_config, ensure_ascii=False))
    except Exception as exc:
        print(f"[facebook][WARN] Facebook config 로그 저장 실패: {exc}", flush=True)
    row = bot_runtime_row()
    if row.get("status") in {"RUNNING", "STARTING"}:
        print("[bot] persisted RUNNING state found; restarting social news bot", flush=True)
        start_bot()
    elif row.get("status") == "STOPPING":
        set_bot_status("STOPPED")
    if job_collector_settings().get("schedulerEnabled"):
        print("[job-collector] persisted scheduler flag found; restarting scheduler", flush=True)
        start_job_scheduler()
    print(f"[llama] {ensure_llama(start_command=True)['message']}", flush=True)
    start_telegram_update_poller()
    server = ThreadingHTTPServer((args.host, args.port), AdminRequestHandler)
    print(f"Admin API listening on http://{args.host}:{args.port}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

